apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Set namespace for all namespaced resources
namespace: sealed-secrets

resources:
- namespace.yaml
- sealed-secrets.yaml
- helm/release.yaml
# Important: This file contains resources with explicit namespace: flux-system
- flux-system-resources.yaml
