---
# Sealed Secrets CRD
# ENVIRONMENT-SPECIFIC: CRD definitions generally remain consistent across environments
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sealedsecrets.bitnami.com
spec:
  group: bitnami.com
  names:
    kind: SealedSecret
    plural: sealedsecrets
    singular: sealedsecret
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            x-kubernetes-preserve-unknown-fields: true
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
---
# Sealed Secrets Controller Deployment
# ENVIRONMENT-SPECIFIC: This deployment configuration can be customized per environment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  # ENVIRONMENT-SPECIFIC: Replicas can be increased for HA in production
  replicas: 1
  selector:
    matchLabels:
      name: sealed-secrets-controller
  template:
    metadata:
      labels:
        name: sealed-secrets-controller
      # ENVIRONMENT-SPECIFIC: Add environment-specific annotations here
      # annotations:
      #   prometheus.io/scrape: "true"
      #   prometheus.io/port: "8080"
    spec:
      # ENVIRONMENT-SPECIFIC: Node selector and tolerations can be added for production
      # nodeSelector:
      #   kubernetes.io/os: linux
      # tolerations:
      # - key: "critical-workload"
      #   operator: "Equal"
      #   value: "true"
      #   effect: "NoSchedule"
      containers:
      - name: sealed-secrets-controller
        # ENVIRONMENT-SPECIFIC: Version should be pinned, especially in production
        image: bitnami/sealed-secrets-controller:v0.24.5
        ports:
        - containerPort: 8080
        # ENVIRONMENT-SPECIFIC: Args can be customized per environment
        args:
        - "--key-prefix=sealed-secrets-key"
        # ENVIRONMENT-SPECIFIC: Add resource limits and requests
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
# Sealed Secrets Service
# ENVIRONMENT-SPECIFIC: Service configuration generally remains consistent
apiVersion: v1
kind: Service
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
  # ENVIRONMENT-SPECIFIC: Add environment-specific annotations
  # annotations:
  #   prometheus.io/scrape: "true"
  #   prometheus.io/port: "8080"
spec:
  selector:
    name: sealed-secrets-controller
  ports:
  - port: 8080
    targetPort: 8080
---
# Service Account
# ENVIRONMENT-SPECIFIC: Service account generally remains consistent
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
---
# RBAC: ClusterRole
# ENVIRONMENT-SPECIFIC: RBAC generally remains consistent across environments
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sealed-secrets-controller
rules:
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
---
# RBAC: ClusterRoleBinding
# ENVIRONMENT-SPECIFIC: RBAC generally remains consistent across environments
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sealed-secrets-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sealed-secrets-controller
subjects:
- kind: ServiceAccount
  name: sealed-secrets-controller
  namespace: sealed-secrets 