apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      version: "0.47.x"
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: flux-system
  values:
    mode: daemonset
    config:
      receivers:
        otlp:
          protocols:
            grpc:
            http:
      processors:
        batch:
          timeout: 10s
      exporters:
        prometheus:
          endpoint: 0.0.0.0:8889
        logging:
          verbosity: detailed
        otlp:
          endpoint: prometheus-stack-kube-prom-prometheus:9090
        s3:
          region: us-east-1
          access_key: minioadmin
          secret_key: minioadmin
          endpoint: minio.minio-system:9000
          bucket: tempo
          path: traces
          s3_force_path_style: true
          insecure: true
      service:
        pipelines:
          metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus, logging]
          traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [logging, s3]
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi 