apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-infrastructure
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: platform-config
  path: ./clusters/vps/staging
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  retryInterval: 1m0s
  wait: true 