apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base policies configuration
resources:
  - ../../../policies

# Common labels for all resources
commonLabels:
  environment: staging
  tier: policies

# Common annotations for staging environment
commonAnnotations:
  environment.type: "staging"
  policies.enforcement: "dryrun"

# Apply the policy patches
patchesStrategicMerge:
  - require-probes-patch.yaml 