apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base network configuration
resources:
- ../../../base/observability/network

# Apply local-specific patches
patches:
# Uncomment and add patches as needed
# - path: patches/serviceMonitor-patch.yaml
#   target:
#     kind: ServiceMonitor
#     name: flux-system 