apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base observability common configuration
resources:
  - ../../../../base/observability/common

# Common labels for all resources
commonLabels:
  environment: production
  tier: observability
  criticality: high

# Common annotations for production
commonAnnotations:
  production-ready: "true"
  backup-policy: "daily"
  security-tier: "critical"
  monitoring.enabled: "true"

# Apply the sources patches
patchesStrategicMerge:
  - sources-patch.yaml 