---
# This is a HelmRelease Custom Resource Definition for MinIO Object Storage
# ENVIRONMENT-SPECIFIC: This may need adjustments based on your GitOps implementation
#
# Installation Options:
# 1. Flux v2: Use this HelmRelease as is (adjust sourceRef namespace if needed)
# 2. ArgoCD: Convert to Application CR or use helm chart directly
# 3. Manual: Use helm CLI with the values.yaml file
#    helm install minio minio/minio --values values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
  annotations:
    # Force reconciliation with a newer timestamp
    reconcile.fluxcd.io/requestedAt: "2025-03-04T11:15:00Z"
    # ENVIRONMENT-SPECIFIC: Additional annotations for different environments
    environment.config/description: "MinIO S3-compatible object storage"
    # ENVIRONMENT-SPECIFIC: Production annotations might include:
    # backup.velero/include: "true"
    # priority.class/tier: "critical"
spec:
  # ENVIRONMENT-SPECIFIC: Adjust interval based on environment
  # - local/dev: shorter intervals (5m)
  # - staging/prod: longer intervals (15m+)
  interval: 5m
  chart:
    spec:
      chart: minio
      # ENVIRONMENT-SPECIFIC: Version pinning is important
      # - local/dev: can use minor version ranges (5.0.x)
      # - staging: should pin to specific patch versions
      # - production: must pin to specific patch versions
      version: 5.0.7
      sourceRef:
        kind: HelmRepository
        name: minio
        # ENVIRONMENT-SPECIFIC: Update namespace if needed for your GitOps setup
        namespace: flux-system
  # Reference to the SealedSecret for credentials
  # ENVIRONMENT-SPECIFIC: Secret management approaches may differ
  # - local/dev: might use plain secrets
  # - staging/production: should use proper secret management (SealedSecrets, Vault, etc.)
  valuesFrom:
    - kind: Secret
      name: minio-credentials
      valuesKey: rootUser
      targetPath: accessKey
    - kind: Secret
      name: minio-credentials
      valuesKey: rootPassword
      targetPath: secretKey
  # ENVIRONMENT-SPECIFIC: Install/upgrade strategy may differ per environment
  # install:
  #   remediation:
  #     retries: 3
  # upgrade:
  #   remediation:
  #     retries: 3
  #     remediateLastFailure: true
  values:
    # These values would be read from the values.yaml file
    # ENVIRONMENT-SPECIFIC: Deployment mode is critical
    # - local/dev: standalone is sufficient
    # - production: distributed for HA
    mode: standalone
    # Credentials are now provided via the SealedSecret
    # accessKey and secretKey are removed from here
    # ENVIRONMENT-SPECIFIC: Storage requirements vary by environment
    persistence:
      enabled: true
      size: 10Gi
    # ENVIRONMENT-SPECIFIC: Resource allocations differ by environment
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
    # ENVIRONMENT-SPECIFIC: Service type may differ by environment
    service:
      type: ClusterIP
    # ENVIRONMENT-SPECIFIC: Ingress settings are very environment-specific
    ingress:
      enabled: true
      path: /
      hosts:
        - minio.local
      tls: []
      # ENVIRONMENT-SPECIFIC: TLS should be configured for staging/production
      # annotations:
      #   cert-manager.io/cluster-issuer: letsencrypt-prod

---
# For reference, this is the HelmRepository CRD that would be used with Flux v2
# ENVIRONMENT-SPECIFIC: Repository configurations may be centralized or environment-specific
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: minio
  namespace: flux-system
  # ENVIRONMENT-SPECIFIC: Add environment-specific annotations if needed
  # annotations:
  #   environment: base
spec:
  # ENVIRONMENT-SPECIFIC: Sync interval may differ by environment
  interval: 1h
  url: https://charts.min.io/ 