apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - common
  - grafana
  - prometheus
  - loki
  - opentelemetry
  - network

patchesStrategicMerge:
  # Override the namespace from observability to monitoring if needed
  # - namespace-patch.yaml 