apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base gatekeeper configuration
resources:
- ../../../../clusters/base/infrastructure/gatekeeper
# Include RBAC resources
- rbac/gatekeeper-rbac.yaml

# Common labels for all resources
commonLabels:
  environment: staging
  tier: infrastructure

# Apply staging-specific patches
patchesStrategicMerge:
- patches/helmrelease-patch.yaml

# Use transformers to exclude the namespace
transformers:
- transformers/remove-namespace.yaml 