apiVersion: v1
kind: Secret
metadata:
  name: supabase-analytics
  namespace: supabase
type: Opaque
stringData:
  CLICKHOUSE_USER: default
  CLICKHOUSE_PASSWORD: password123
  CLICKHOUSE_DB: analytics
  CLICKHOUSE_HOST: clickhouse.supabase.svc.cluster.local 