apiVersion: v1
kind: Secret
metadata:
  name: supabase-db
  namespace: supabase
type: Opaque
stringData:
  POSTGRES_PASSWORD: postgres_password
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  PGPASSWORD: postgres_password
  PGUSER: postgres
  PGDATABASE: postgres 