apiVersion: v1
kind: Secret
metadata:
  name: supabase-jwt
  namespace: supabase
type: Opaque
stringData:
  JWT_SECRET: super_secret_jwt_token_with_at_least_32_characters
  ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiJ9.ZopqoUjlYrXLn3FpKiRJIKzusXkqHQBPo2TCFWSMQnI
  SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIn0.M2d2z4SFn5C1AqsKYAhJWuGFJI5viMQRJqcbJTgGR_8 