apiVersion: v1
kind: Secret
metadata:
  name: supabase-s3
  namespace: supabase
type: Opaque
stringData:
  PGSODIUM_SECRET_KEY: d2ViLXNwcmlu
  STORAGE_BACKEND: s3
  S3_ENDPOINT: http://minio.minio-system.svc.cluster.local:9000
  S3_BUCKET: supabase-storage
  S3_REGION: us-east-1 
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin 