apiVersion: v1
kind: Secret
metadata:
  name: supabase-smtp
  namespace: supabase
type: Opaque
stringData:
  SMTP_ADMIN_EMAIL: admin@example.com
  SMTP_HOST: smtp.example.com
  SMTP_PORT: "587"
  SMTP_USER: smtpuser
  SMTP_PASS: smtppass
  SMTP_SENDER_NAME: "Supabase Local" 