apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sRequiredLabels
metadata:
  name: require-app-team-labels
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: ["apps"]
        kinds: ["Deployment", "StatefulSet"]
    excludedNamespaces: 
      - kube-system
      - flux-system
      - gatekeeper-system
      - supabase
  parameters:
    labels: ["app", "team", "environment"] 