apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio-system
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: "5.0.x"
      sourceRef:
        kind: HelmRepository
        name: minio
        namespace: flux-system
  values:
    mode: standalone
    persistence:
      enabled: true
      size: 20Gi
    resources:
      requests:
        memory: 512Mi
        cpu: 250m
      limits:
        memory: 1Gi
        cpu: 500m
    rootUser: "minioadmin"  # In production, use a sealed secret
    rootPassword: "minioadmin"  # In production, use a sealed secret
    buckets:
      - name: loki
        policy: public
        purge: false
      - name: thanos
        policy: public
        purge: false
      - name: prometheus
        policy: public
        purge: false
      - name: tempo
        policy: public
        purge: false
      - name: logs
        policy: public
        purge: false
      - name: backups
        policy: public
        purge: false
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
      hosts:
        - name: minio.local
          path: /
      tls:
        - secretName: minio-tls
          hosts:
            - minio.local
    consoleIngress:
      enabled: true
      ingressClassName: nginx
      annotations:
        cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
      hosts:
        - name: minio-console.local
          path: /
      tls:
        - secretName: minio-console-tls
          hosts:
            - minio-console.local 