---
# Staging Environment: IP Address Pool Configuration
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  # Staging environment IP range - typically aligned with staging network
  # This range should be allocated specifically for LoadBalancer services
  addresses:
  - 10.10.10.200-10.10.10.250  # PLACEHOLDER: Adjust based on your staging network 