apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base sealed-secrets configuration
resources:
  - ../../../../base/infrastructure/sealed-secrets

# Common labels for all resources
commonLabels:
  environment: staging
  tier: infrastructure

# Common annotations for staging
commonAnnotations:
  monitoring.enabled: "true"

# Apply the values patch to the HelmRelease
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: sealed-secrets
        namespace: sealed-secrets
        annotations:
          environment.config/description: "Sealed Secrets controller for staging environment"
      spec:
        # Staging environment specific settings
        interval: 15m  # Less frequent reconciliation for staging
        chart:
          spec:
            version: "2.10.0"  # Pin to specific version for stability
        install:
          remediation:
            retries: 3
        upgrade:
          remediation:
            retries: 3
        values:
          $patch: merge
          $(cat values-patch.yaml | indent 10)
    target:
      kind: HelmRelease
      name: sealed-secrets
      namespace: sealed-secrets 