apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- patches/ip-pool-config.yaml
- ../../../../clusters/base/infrastructure/metallb/namespace.yaml
- ../../../../clusters/base/infrastructure/metallb/release.yaml
commonLabels:
  environment: staging
  tier: infrastructure
commonAnnotations:
  monitoring.enabled: "true"
patchesStrategicMerge:
- patches/helmrelease-patch.yaml 
# Use transformers to exclude the namespace
transformers:
- transformers/remove-namespace.yaml
