---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: supabase-analytics
  namespace: supabase
spec:
  encryptedData:
    apiKey: AgAkGytA9z8nIrYPZTBJl9dGsvEz+oj25jyiAyjbYiiYfLqLFghHx6QNKvrpT5VDG9SVrxniqlQhVKU2y+LCKDqo2ZnTV3TRDDEvTSFcVXeeOh9BwcdULcd+aKAd7bTDBrBW0osis7B80e/n916S/3yUR7soQcCiFN3oUMxTcOSraC3LUMk/GPPAQi9nzAThypqkLZ7/BfOmMSepqtQajDkTtAyfVOAOtONKwvjtt5vZTRiopKRZV4Un70jxdDC5LN8voKFZuRMuIY64SnRvU+SIMYz2TiYnWwmYblb1M3YVwCnqfPiTc7eR7L5O4kqLZliCrvd5+G0gx72yI4QaRAbJoI/4/ZnM42/VDjbSP+pVU/KOcF1U4R7I32rL+LQvXJ5/pzx7N7PfkqyStKfakhUMmlTnVhl1OLEkbD+XAwk/CqBNT/wKGqAdROeaiR27dRHhDcWh9NWrjlXoDSNcwzFzonmiANEULdfWCgLGXSsENGeXgE6LNNLCgaGh4N8FvgiCkMY+OXSTI8I+MmMoR5fYvA//gOlrrza7lo02eAJoIRecXBp2Xg0eaQ4tUU0TlcjgoccE54QTXUt5S+BbzmeFpekjy11U0LONBd8hTNIhG5+VZeNxn1d94JB/Hesx1ahdVM7lBTHZ2XWs212ppBeBOVLMhE+E+HP5bOelAoCs9ecfMp3QkJgSu4R2C0IGx4nQmku0anh2Q1BjTJyHjR5QHVpbewUrmT7holjSak3Dsa05mIfdKUI=
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: supabase
      name: supabase-analytics
      namespace: supabase
    type: Opaque
