---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: supabase-s3
  namespace: supabase
spec:
  encryptedData:
    accessKey: AgCnrPlWzqvVHNScwEr3tveknT5FA+IFlQl6mqa8xYdxloboi7RoxHD3RCoXRcYD/BMfE/kdGK7o4rZg63qtGBzInn3Q1iwm6ZjCNOtbuR9NCgEQb9c00KVQzO4HxBgRjg7WTDcp+E0sXC5lOf34LVSN9iTmK0ZZ/jhAqMxroeOS1lC4E+5c4BoUAPSN3/CsSpOFeibmWIl2y57A6BVxG+PYeGjqeCUE2jmbDzmbv4yZCewlTHMn4152Wu5rngr5v4B/gWs0+LpYAomzPNfhNdzXNJr97mx0SPYzelGGNQpFg7HuifEVOTODyPrBLE8/Ukrr+kXTrAcWtueKFV3nZTnUwROlCrudXaXvjGoMQGKX5rj1OlIM1de2/YTgkvOStkEtvpUzaJBxG3Pvx99REU6Ke8iZTdi9HKmGXvIvSLNvp+CrLPVPwLnMrKMLgLtgBPrx1kKbTEIdqi2q1nOb4bvHU0Wy/FM1X0I2DXZaido7EbSKXjF+R8fyKN4gwhDogh2a8rlJL0gjX1T/g63of0D/VWIZuotZuz8daxuKqU/bCwx+HNNAfnrS3mEaQAJvarkrbrR5WYprDpa9/6W371/JvyIXTc4vEnxSNlrsjL4rDusQbTRSRGxvDvDvNdqBngGI+jcG5I2YQNamGfb9ZKqPE/GznNmwOX95HPNbhe/NqufFPxBrof+JmdhhaMAfieYWpQ9wKXLvNCbHlGA/AeM=
    keyId: AgA/rdgnwJGCFgg9a2Llsj/2csVA+OofZc3RBkYOEeKZCeW6K+aqc/RvV40Mf1X9wSw/C4huiaRjnuyMMdO2yUWaB8wcLgkxXLLSw5FtnNynGE73Zt6xrEpgTWnxd69oBphf3fQ8X3kLnJtrMe24FpQOS75Xhzdo0ftrC3lVEaydp/Obzkn/EMz/pHEl9RHAbFijosFVaknecAoHa3KyTzpN3216ksMkJ/pAfk0YbtsP3fVwwE5Gv3X/k+eu+3UVGMmLYbSZqZkySfghbKZrtT5QfievV6Tn/Yglwup5ARsW9GvOc9dRg/mEca1TswcSjP4OXuXz1RaGnQ71xEt1ycEw3U3OR3aM3j5pEqC12I7IvY7UOe3EvhIMJOGCIq8FkebWePKtSuZTfxbODmFsrbBYbjo1Rj1ypAYySdVrys6z2I2BuNVCksy99Ck7blNlxS+ePdJbmh6YnIWXodEUzy9PZseDRYwVsbSOxn0YIVpQkPJ04GKgYlwolaE8kADkLd8nYsGUWQx+Yncv9ycNPbevghGM7uNA+oR/IoENXJrXVuLI6lLm4SXNuCBq4gHLA3MRNvp9/xCpvvs8QweoS8J438r/spoVBxgfEIf7Zu1LsVDxylWvu6T8i1SJMP1P0SSn1rN6trag/ZzqdwuKaEf1CU56aW1UX6Nwe9UZxxoD9MS4RrcXsqOpqbblxm2h2vel2S6cd8CeOwB5eA==
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/part-of: supabase
      name: supabase-s3
      namespace: supabase
    type: Opaque
