apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base sealed-secrets configuration
resources:
  - ../../../../base/infrastructure/sealed-secrets

# Common labels for all resources
commonLabels:
  environment: production
  tier: infrastructure
  criticality: high

# Common annotations for production
commonAnnotations:
  production-ready: "true"
  backup-policy: "daily"
  security-tier: "critical"
  monitoring.enabled: "true"

# Apply the values patch to the HelmRelease
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: sealed-secrets
        namespace: sealed-secrets
        annotations:
          fluxcd.io/automated: "false"  # Disable automated updates in production
          environment.config/description: "Sealed Secrets controller for production environment"
      spec:
        # Production environment specific settings
        interval: 30m  # Less frequent reconciliation for production
        chart:
          spec:
            version: "2.10.0"  # Pin to specific version for production stability
        # Add Install/Upgrade strategies for production
        install:
          remediation:
            retries: 5
        upgrade:
          remediation:
            retries: 5
            remediateLastFailure: true
          crds: Skip
        values:
          $patch: merge
          $(cat values-patch.yaml | indent 10)
    target:
      kind: HelmRelease
      name: sealed-secrets
      namespace: sealed-secrets
  
  # Optional: Add additional customizations specific to production
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: sealed-secrets
        namespace: sealed-secrets
      spec:
        template:
          metadata:
            annotations:
              critical-component: "true"
              cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
    target:
      kind: Deployment
      name: sealed-secrets
      namespace: sealed-secrets 