apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/observability/opentelemetry
commonLabels:
  environment: staging
  component: observability
commonAnnotations:
  monitoring.enabled: "true"
patchesStrategicMerge:
  - patches/config-patch.yaml 