---
# This is a HelmRelease Custom Resource for Sealed Secrets
# ENVIRONMENT-SPECIFIC: This may need adjustments based on your GitOps implementation
#
# Installation Options:
# 1. Flux v2: Use this HelmRelease as is (adjust sourceRef namespace if needed)
# 2. ArgoCD: Convert to Application CR or use helm chart directly
# 3. Manual: Use helm CLI with values
#    helm install sealed-secrets sealed-secrets/sealed-secrets --values values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
  annotations:
    # This will force Flux to restart the deployment and pick up changes
    reconcile.fluxcd.io/requestedAt: "2025-03-04T09:45:00Z"
    # ENVIRONMENT-SPECIFIC: Additional annotations for different environments
    environment.config/description: "Sealed Secrets controller for secure secret management"
    # ENVIRONMENT-SPECIFIC: Production annotations might include:
    # backup.velero/include: "true"
    # security-tier: "critical"
spec:
  # ENVIRONMENT-SPECIFIC: Adjust interval based on environment
  # - local/dev: shorter intervals (5m)
  # - staging/prod: longer intervals (15m+)
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      # ENVIRONMENT-SPECIFIC: Version pinning is important for security tools
      # - local/dev: can use minor version ranges
      # - staging: should pin to specific patch versions
      # - production: must pin to specific patch versions
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        # ENVIRONMENT-SPECIFIC: Update namespace if needed for your GitOps setup
        namespace: flux-system
  # ENVIRONMENT-SPECIFIC: Install/upgrade strategy may differ per environment
  # install:
  #   remediation:
  #     retries: 3
  # upgrade:
  #   remediation:
  #     retries: 3
  #     remediateLastFailure: true
  values:
    # These values would be read from the values.yaml file
    fullnameOverride: sealed-secrets
    namespace: sealed-secrets
    
    # ENVIRONMENT-SPECIFIC: Service account configuration
    # This is generally stable across environments
    serviceAccount:
      create: true
      name: sealed-secrets-controller
      annotations: {}
    
    # ENVIRONMENT-SPECIFIC: RBAC settings
    # These permissions are generally consistent across environments
    rbac:
      create: true
    
    # ENVIRONMENT-SPECIFIC: Key management
    # - production may need different key rotation policies
    secretName: sealed-secrets-key
    
    # ENVIRONMENT-SPECIFIC: Resource allocation
    # - local/dev: minimal resources
    # - staging: medium resources
    # - production: higher resources for better performance
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    
    # ENVIRONMENT-SPECIFIC: Controller configuration
    # - Different environments may need different log levels or flags
    controller:
      # Ensure no problematic flags are included
      args:
        - --key-prefix=sealed-secrets-key
        - --update-status
      # Explicitly set the command
      command:
        - controller
      # ENVIRONMENT-SPECIFIC: Replicas for HA in production
      # replicas: 1  # Increase to 2+ for production
    
    # ENVIRONMENT-SPECIFIC: Monitoring configuration
    # metrics:
    #   serviceMonitor:
    #     enabled: false # Set to true for staging/production
    #     additionalLabels:
    #       release: prometheus

    # ENVIRONMENT-SPECIFIC: Security Context
    # Stricter settings in production
    # securityContext:
    #   runAsNonRoot: true
    #   runAsUser: 1001
    #   fsGroup: 65534

    # ENVIRONMENT-SPECIFIC: HA settings for production
    # podAntiAffinity: false # Set to true for production

---
# For reference, this is the HelmRepository CRD that would be used with Flux v2
# ENVIRONMENT-SPECIFIC: Repository configurations may be centralized or environment-specific
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
  # ENVIRONMENT-SPECIFIC: Add environment-specific annotations if needed
  # annotations:
  #   environment: base
spec:
  # ENVIRONMENT-SPECIFIC: Sync interval may differ by environment
  interval: 1h
  url: https://bitnami-labs.github.io/sealed-secrets 