apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base gatekeeper configuration
resources:
- ../../../base/infrastructure/gatekeeper

# Apply local-specific patches
patchesStrategicMerge:
# Uncomment and add patches as needed
# - patches/deployment-patch.yaml
# - patches/service-patch.yaml

# Import local-specific values
configMapGenerator:
- name: gatekeeper-values
  behavior: merge
  files:
  - values.yaml=helm/values.yaml
