apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base vault configuration
resources:
  - ../../../../base/infrastructure/vault

# Common labels for all resources
commonLabels:
  environment: local
  tier: infrastructure

# Generate the values ConfigMap with our local values
configMapGenerator:
  - name: vault-values
    behavior: merge
    files:
      - values.yaml=values-patch.yaml

# Apply patches
patchesStrategicMerge:
  - ingress-patch.yaml

# Apply the values patch to the HelmRelease
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: vault
        namespace: vault
      spec:
        # Local environment specific settings
        interval: 1m  # More frequent reconciliation for development
    target:
      kind: HelmRelease
      name: vault
      namespace: vault 