# Production Environment - Chart Verification Secret
# This is a placeholder for the chart GPG verification keys
# In a real production environment, use a tool like SealedSecrets or Vault

apiVersion: v1
kind: Secret
metadata:
  name: supabase-chart-gpg-keys
  namespace: supabase
  labels:
    environment: production
    tier: applications
    criticality: high
  annotations:
    environment.type: "production"
type: Opaque
# This is a placeholder - in production, use real GPG keys
stringData:
  pgp-public-keys: |
    # Replace with actual GPG public keys for chart verification
    # Example: mQINBGBKT+0BEADCh6SSWsHsbz5Gj9TDvq/m5CMpCpvVHYBOZ9SxYVX2kQ7m
    # You would typically manage this with external-secrets or sealed-secrets
  pgp-public-keys-fingerprints: |
    # Add fingerprints of the GPG keys
    # Example: 72A70DDD8CB851CDB1B52C9B29142AF4F55C66C9 