apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base supabase configuration
resources:
  - ../../../supabase
  # Add production-specific resources
  - chart-gpg-keys-secret.yaml

# Common labels for all resources
commonLabels:
  environment: production
  tier: applications
  criticality: high

# Common annotations for production environment
commonAnnotations:
  environment.type: "production"
  monitoring.enabled: "true"
  backup.enabled: "true"
  security-tier: "critical"
  pagerduty.enabled: "true"

# Apply the values patches
patchesStrategicMerge:
  - helmrelease-patch.yaml

# Override the values ConfigMap
configMapGenerator:
  - name: supabase-values
    behavior: merge
    files:
      - values.yaml=values-patch.yaml 