# Local Environment Configuration for NGINX Ingress
controller:
  # Use NodePort for local development
  service:
    type: NodePort
  
  # Minimal resources for local development
  resources:
    limits:
      cpu: 500m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  # Single replica for local development
  replicaCount: 1
  
  # Additional config for local development
  config:
    # Enable status page for debugging
    enable-underscores-in-headers: "true"
    log-format-upstream: '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $request_length $request_time [$proxy_upstream_name] [$proxy_alternative_upstream_name] $upstream_addr $upstream_response_length $upstream_response_time $upstream_status $req_id'
  
  # Local-specific annotations
  podAnnotations:
    environment: "local"
  
  # Disable metrics for local development
  metrics:
    enabled: false

# Disable default backend in local
defaultBackend:
  enabled: false

# Disable SSL redirect for easier local development
config:
  ssl-redirect: "false" 