apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base vault configuration
resources:
- ../../../../base/infrastructure/vault

# Common labels for all resources
commonLabels:
  environment: staging
  tier: infrastructure

# Common annotations for staging
commonAnnotations:
  monitoring.enabled: "true"

# Apply staging-specific patches
patchesStrategicMerge:
- patches/helmrelease-patch.yaml 