apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base supabase configuration
resources:
  - ../../../supabase

# Common labels for all resources
commonLabels:
  environment: local
  tier: applications

# Common annotations for local environment
commonAnnotations:
  environment.type: "development"

# Apply the values patches
patchesStrategicMerge:
  - helmrelease-patch.yaml

# Override the values ConfigMap
configMapGenerator:
  - name: supabase-values
    behavior: merge
    files:
      - values.yaml=values-patch.yaml 