apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Namespace definitions - should be first (GitOps managed)
  - namespaces/
  # Core infrastructure components
  - cert-manager/
  - sealed-secrets/
  - vault/
  - ingress/
  - gatekeeper/
  - minio/
  - metallb/
  # Observability components
  - prometheus/
  - loki/
  - tempo/
  # Additional components
  - policy-engine/
  - security/ 