apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base gatekeeper configuration
resources:
  - ../../../../base/infrastructure/gatekeeper

# Common labels for all resources
commonLabels:
  environment: staging
  tier: infrastructure

# Merge our values with the base values
configMapGenerator:
  - name: gatekeeper-values
    behavior: merge
    files:
      - values.yaml=values-patch.yaml 