---
# This is a HelmRelease Custom Resource Definition
# In a GitOps setup with Flux or ArgoCD, this would be managed by the GitOps controller
# For manual implementation, you would use: helm template sealed-secrets/sealed-secrets --values values.yaml | kubectl apply -f -
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
  annotations:
    # This will force Flux to restart the deployment and pick up changes
    reconcile.fluxcd.io/requestedAt: "2025-03-04T09:45:00Z"
spec:
  interval: 5m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.10.0
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: flux-system
  values:
    # These values would be read from the values.yaml file
    fullnameOverride: sealed-secrets
    namespace: sealed-secrets
    
    # Service account configuration - ensuring it's properly set
    serviceAccount:
      create: true
      name: sealed-secrets-controller
      annotations: {}
    
    # Role & Role Bindings to ensure proper permissions
    rbac:
      create: true
    
    secretName: sealed-secrets-key
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    
    # Fix for the crashing controller - explicitly override args
    controller:
      # Ensure no problematic flags are included
      args:
        - --key-prefix=sealed-secrets-key
        - --update-status
      # Explicitly set the command
      command:
        - controller

---
# For reference, this is the HelmRepository CRD that would be used with Flux v2
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  interval: 1h
  url: https://bitnami-labs.github.io/sealed-secrets 