apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  values:
    controller:
      # Local-specific values
      resources:
        requests:
          memory: "64Mi"
          cpu: "50m"
        limits:
          memory: "128Mi"
          cpu: "100m"
      # Use single replica for local development
      replicaCount: 1
      # Use NodePort instead of LoadBalancer for local development
      service:
        type: NodePort
