apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supabase

resources:
  - ../../../base/applications/supabase

patches:
  - path: patches/helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: supabase

# Generate ConfigMap from values.yaml file
configMapGenerator:
- name: supabase-values
  behavior: replace
  files:
  - values.yaml=helm/values.yaml
  # Add timestamp to ensure ConfigMap gets updated
  literals:
  - last_update_timestamp="2025-03-06T19:22:00Z"

labels:
  - pairs:
      app.kubernetes.io/part-of: supabase 