apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supabase

resources:
  - ../../../base/applications/supabase
  # Sealed secrets for local development
  - sealed-secrets

patches:
  - path: patches/helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: supabase

# Replace the ConfigMap generated in the base kustomization
configMapGenerator:
- name: supabase-values
  behavior: replace
  files:
  - values.yaml=helm/values.yaml
  # Add timestamp to ensure ConfigMap gets updated
  literals:
  - last_update_timestamp="2025-03-06T19:44:00Z"

# This ensures kustomize doesn't add a hash suffix to the ConfigMap name
generatorOptions:
  disableNameSuffixHash: true

labels:
  - pairs:
      app.kubernetes.io/part-of: supabase 