apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base policies configuration
resources:
  - ../../../policies

# Common labels for all resources
commonLabels:
  environment: local
  tier: policies

# Common annotations for local environment
commonAnnotations:
  environment.type: "development"
  policies.enforcement: "warn"

# Apply the policy patches
patchesStrategicMerge:
  - require-probes-patch.yaml 