apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux-alerts
  namespace: monitoring
spec:
  groups:
  - name: flux-system
    rules:
    - alert: FluxGitOperationFailed
      expr: sum by (namespace, name) (rate(gotk_source_git_operation_failed_total[5m])) > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Git operation failed in {{ $labels.namespace }}/{{ $labels.name }}"
        description: "Git repository operations are failing, which may indicate network connectivity issues or authentication problems."
        
    - alert: FluxReconciliationFailures
      expr: sum by (namespace, name) (rate(gotk_reconcile_error_total{controller=~"gitrepository|helmrepository|kustomization|helmrelease"}[5m])) > 0
      for: 10m
      labels:
        severity: warning
      annotations:
        summary: "Flux reconciliation failures in {{ $labels.namespace }}/{{ $labels.name }}"
        description: "Flux reconciliation failures detected, which may indicate network connectivity issues or issues with remote repositories."
        
    - alert: HighNetworkLatency
      expr: histogram_quantile(0.95, sum(rate(gotk_source_git_operation_duration_seconds_bucket[5m])) by (le, namespace, name)) > 10
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: "High network latency for Git operations in {{ $labels.namespace }}/{{ $labels.name }}"
        description: "95th percentile of Git operation duration is high, which may indicate network connectivity issues." 