apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supabase

resources:
  - namespace.yaml
  - gitrepository.yaml
  - helmrelease.yaml
  - values.yaml
  - sealed-secrets/sealed-jwt-secret.yaml
  - sealed-secrets/sealed-dashboard-secret.yaml
  - sealed-secrets/sealed-db-secret.yaml
  - sealed-secrets/sealed-smtp-secret.yaml
  - sealed-secrets/sealed-analytics-secret.yaml
  - sealed-secrets/sealed-s3-secret.yaml

commonLabels:
  app.kubernetes.io/part-of: supabase 