apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
  - namespace.yaml
  - buckets.yaml
  - helm/release.yaml

# Import values from the values file
configMapGenerator:
  - name: minio-values
    files:
      - values.yaml=helm/values.yaml
