apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../base/infrastructure/security
commonLabels:
  environment: staging
  tier: infrastructure
commonAnnotations:
  monitoring.enabled: "true"
patchesStrategicMerge:
- patches/helmrelease-patch.yaml 