apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common labels for all resources
commonLabels:
  environment: staging
  managed-by: kustomize

resources:
  # Include specific applications for staging
  - supabase 