apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supabase

resources:
  - namespace.yaml
  - gitrepository.yaml
  - helmrelease.yaml

# Import values from the values file
configMapGenerator:
- name: supabase-values
  files:
  - values.yaml=helm/values.yaml 