apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/infrastructure/policy-engine

patches:
  - path: patches/helmrelease-patch.yaml
    target:
      kind: HelmRelease
      name: gatekeeper 