apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: minio

resources:
- base
# Reference to Helm-based resources
- helm/release.yaml

# Import values from the values file
configMapGenerator:
- name: minio-values
  namespace: minio
  files:
  - values.yaml=helm/values.yaml 