apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: minio
spec:
  encryptedData:
    # These values need to be sealed with kubeseal
    # Example command:
    # kubectl create secret generic minio-credentials --namespace=minio --from-literal=rootUser=minioadmin --from-literal=rootPassword=securepassword --dry-run=client -o yaml | kubeseal > sealed-secret.yaml
    rootUser: AgBy3i4OJSWK+PiTySYZZA9rO0n8...
    rootPassword: AgCrmD5MVknVdLqGaK0uG+H8N...
  template:
    metadata:
      name: minio-credentials
      namespace: minio
    type: Opaque 