apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../clusters/base/infrastructure/namespaces

# Add staging-specific labels to all namespaces
commonLabels:
  environment: staging 