apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base ingress configuration
resources:
  - ../../../../base/infrastructure/ingress

# Common labels for all resources
commonLabels:
  environment: production
  tier: infrastructure
  criticality: high

# Common annotations for all resources
commonAnnotations:
  production-ready: "true"
  backup-policy: "daily"
  security-tier: "critical"
  monitoring.enabled: "true"

# Apply the values patch to the HelmRelease
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: ingress-nginx
        namespace: ingress-nginx
        annotations:
          fluxcd.io/automated: "false"  # Disable automated updates in production
          "meta.helm.sh/release-name": "ingress-nginx"
          "meta.helm.sh/release-namespace": "ingress-nginx"
      spec:
        # Longer reconciliation interval for production
        interval: 30m
        # Specific chart version for production stability
        chart:
          spec:
            version: "4.4.2"  # Pin to specific version for production
        # Increase retry attempts for production
        install:
          remediation:
            retries: 5
        upgrade:
          remediation:
            retries: 5
        values:
          $patch: merge
          $(cat values-patch.yaml | indent 10)
    target:
      kind: HelmRelease
      name: ingress-nginx 