# Values for MinIO Helm chart
# Reference: https://github.com/minio/minio/tree/master/helm/minio

# MinIO is deployed as infrastructure component for object storage
# It provides S3-compatible storage for the cluster

# Mode can be standalone or distributed
mode: standalone

# Access credentials
# SECURITY NOTE: Credentials are now managed via SealedSecrets
# Do not store sensitive information in this file

# Persistence configuration
persistence:
  enabled: true
  size: 10Gi
  storageClass: ""

# Resource limits and requests
resources:
  requests:
    memory: "256Mi"
    cpu: "100m"
  limits:
    memory: "512Mi"
    cpu: "500m"

# Service configuration
service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - minio.local
  tls: []

# MinIO console (UI)
console:
  enabled: true

# Buckets to create on startup
buckets:
  - name: example-bucket
    policy: none
    purge: false
  - name: logs
    policy: none
    purge: false
  - name: metrics
    policy: none
    purge: false
  - name: traces
    policy: none
    purge: false
  - name: alerts
    policy: none
    purge: false

# Metrics configuration
metrics:
  serviceMonitor:
    enabled: false

# Health check probes
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 20

readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10

# Network policy
networkPolicy:
  enabled: true
  allowExternal: true

# Security context
securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
