apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: grafana
      version: "6.x"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: flux-system
  values:
    persistence:
      enabled: true
      size: 1Gi
    service:
      type: ClusterIP 