# Local Environment - Minimal Resources Configuration for Prometheus
# This patch reduces resource usage for local development environments

prometheus:
  prometheusSpec:
    # Reduced retention time for local development
    retention: 1d
    # Single replica for local development
    replicas: 1
    # Reduced resource requirements
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    # Disable persistent storage for local development
    storageSpec: null
    # Faster scrape intervals for quicker feedback in development
    scrapeInterval: 30s
    # Disable Thanos sidecar for local development
    thanos: null

# Disable Alertmanager for local development
alertmanager:
  enabled: false

# Disable Grafana as it's deployed separately
grafana:
  enabled: false

# Minimal resources for kube-state-metrics
kubeStateMetrics:
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m

# Minimal resources for node-exporter
nodeExporter:
  resources:
    requests:
      memory: 32Mi
      cpu: 25m
    limits:
      memory: 64Mi
      cpu: 50m 