apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base
# Reference to Helm-based resources
- helm/release.yaml

# Import values from the values file
configMapGenerator:
- name: example-app-values
  files:
  - values.yaml=helm/values.yaml 