# Values for MinIO Helm chart
# Reference: https://github.com/minio/minio/tree/master/helm/minio

# Specify the deployment mode
mode: standalone

# Access keys
accessKey: minioadmin
secretKey: minioadmin

# Specify the image
image:
  repository: minio/minio
  tag: RELEASE.2023-12-14T18-51-57Z
  pullPolicy: IfNotPresent

# Number of nodes
replicas: 1

# Resource limits and requests
resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m

# Persistence
persistence:
  enabled: false
  size: 10Gi
  storageClass: ""

# Service
service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

# Console
consoleService:
  type: ClusterIP
  port: 9001

# Ingress
ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
  path: /
  hosts:
    - minio.local
  tls:
    - secretName: minio-tls
      hosts:
        - minio.local

# Metrics
metrics:
  serviceMonitor:
    enabled: false

# Readiness and liveness probes
readinessProbe:
  initialDelaySeconds: 10
  periodSeconds: 10
  httpGet:
    path: /minio/health/ready
    port: 9000
livenessProbe:
  initialDelaySeconds: 30
  periodSeconds: 20
  httpGet:
    path: /minio/health/live
    port: 9000

# Network policy
networkPolicy:
  enabled: true
  allowExternal: true

# Security context
securityContext:
  enabled: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000 