apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: loki-stack
      version: "2.9.x"
      sourceRef:
        kind: HelmRepository
        name: grafana-loki
        namespace: flux-system
  values:
    loki:
      persistence:
        enabled: false  # We'll use MinIO instead of PVCs
      storage:
        bucketNames:
          chunks: loki
          ruler: loki
          admin: loki
        type: s3
        s3:
          endpoint: minio.minio-system:9000
          region: us-east-1
          secretAccessKey: minioadmin  # In production, use a sealed secret
          accessKeyId: minioadmin      # In production, use a sealed secret
          s3ForcePathStyle: true
          insecure: true
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    promtail:
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
    grafana:
      enabled: false  # Grafana is deployed as part of the Prometheus stack 