apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  # Staging environment specific settings
  interval: 15m  # Less frequent reconciliation for staging
  values:
    # Configure prometheus
    prometheus:
      prometheusSpec:
        resources:
          requests:
            memory: 1Gi
            cpu: 200m
          limits:
            memory: 2Gi
            cpu: 500m
        retention: 15d
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              resources:
                requests:
                  storage: 20Gi
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - prometheus.staging.boldorigins.io
        tls:
          - hosts:
              - prometheus.staging.boldorigins.io
    # Configure alertmanager
    alertmanager:
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - alertmanager.staging.boldorigins.io
        tls:
          - hosts:
              - alertmanager.staging.boldorigins.io
    # Configure Grafana
    grafana:
      resources:
        requests:
          memory: 128Mi
          cpu: 50m
        limits:
          memory: 256Mi
          cpu: 100m
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - grafana.staging.boldorigins.io
        tls:
          - hosts:
              - grafana.staging.boldorigins.io 