apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base ingress configuration
resources:
- ../../../base/infrastructure/ingress

# Apply staging-specific patches
patchesStrategicMerge:
- patches/helmrelease-patch.yaml 
# Use transformers to exclude the namespace
transformers:
- transformers/remove-namespace.yaml
