apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: supabase
  namespace: supabase
  labels:
    app: supabase
    environment: local
    team: infrastructure
  annotations:
    # Force certain labels to be added to all resources
    helm.toolkit.fluxcd.io/common-labels: |
      app: supabase
      environment: local
      team: infrastructure
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: ./charts/supabase
      sourceRef:
        kind: GitRepository
        name: supabase
        namespace: supabase
      interval: 1m
  install:
    remediation:
      retries: 1
  upgrade:
    remediation:
      retries: 1
      remediateLastFailure: true
    cleanupOnFail: true
  releaseName: supabase
  valuesFrom:
    - kind: ConfigMap
      name: supabase-values
      valuesKey: values.yaml 