apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supabase

resources:
  - namespace.yaml
  - gitrepository.yaml
  - helmrelease.yaml
  - values.yaml
  - sealed-secrets/sealed-jwt-secret.yaml

commonLabels:
  app.kubernetes.io/part-of: supabase 