apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supabase

resources:
  - namespace.yaml
  - gitrepository.yaml
  - helmrelease.yaml
  - values.yaml
  - secrets/

labels:
  - pairs:
      app.kubernetes.io/part-of: supabase 