apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-values
  namespace: supabase
data:
  values.yaml: |
    # Default values for Supabase
    # PostgreSQL configuration
    postgres:
      enabled: true
      image:
        repository: supabase/postgres
        tag: 15.8.1.046
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 1Gi
      persistence:
        enabled: true
        size: 20Gi

    # Storage configuration
    storage:
      enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi
      # Use MinIO service from our cluster
      environment:
        STORAGE_BACKEND: s3
        GLOBAL_S3_PROTOCOL: http
        GLOBAL_S3_ENDPOINT: http://minio.minio.svc.cluster.local:9000
        GLOBAL_S3_FORCE_PATH_STYLE: true

    # API configuration
    api:
      enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Auth configuration
    auth:
      enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Studio (Dashboard) configuration
    studio:
      enabled: true
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Ingress configuration
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt-staging
      hosts:
        - host: supabase.local
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: supabase-tls
          hosts:
            - supabase.local

    # Secret configuration
    # In production, you should replace these with SealedSecrets
    secret:
      existingSecret: supabase-jwt-secret
      existingSecretKeys:
        anonKey: anonKey
        serviceKey: serviceKey
        secret: jwtSecret
      
      # Other secrets
      smtp:
        username: your-mail@example.com
        password: example123456
      dashboard:
        username: admin
        password: change_me_immediately
      db:
        username: postgres
        password: postgres_password
        database: postgres
      analytics:
        apiKey: your-super-secret-and-long-logflare-key
      # S3 configuration - use MinIO credentials
      s3:
        keyId: minio-access-key
        accessKey: minio-secret-key

    # Disable MinIO since we're using the external MinIO deployment
    minio:
      enabled: false
