apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-values
  namespace: supabase
data:
  values.yaml: |
    # Default values for Supabase
    
    # Secret configuration
    secret:
      # JWT secret
      existingSecret: supabase-jwt
      existingSecretKeys:
        anonKey: anonKey
        serviceKey: serviceKey
        secret: jwtSecret
      
      # Other secrets - using SealedSecrets for improved security
      existingSmtpSecret: supabase-smtp
      existingSmtpSecretKeys:
        username: username
        password: password
      
      existingDashboardSecret: supabase-dashboard
      existingDashboardSecretKeys:
        username: username
        password: password
      
      existingDbSecret: supabase-db
      existingDbSecretKeys:
        username: username
        password: password
        database: database
      
      existingAnalyticsSecret: supabase-analytics
      existingAnalyticsSecretKeys:
        apiKey: apiKey
      
      existingS3Secret: supabase-s3
      existingS3SecretKeys:
        keyId: keyId
        accessKey: accessKey

    # PostgreSQL configuration
    db:
      enabled: true
      image:
        repository: supabase/postgres
        tag: 15.1.0.147
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        initialDelaySeconds: 3
      persistence:
        enabled: true
        size: 20Gi
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 250m
          memory: 1Gi

    # Studio configuration
    studio:
      enabled: true
      image:
        tag: 20240326-5e5586d
      environment:
        STUDIO_DEFAULT_ORGANIZATION: "My Organization"
        STUDIO_DEFAULT_PROJECT: "My Project"
        SUPABASE_PUBLIC_URL: http://supabase.local/
        NEXT_PUBLIC_ENABLE_LOGS: "true"
      livenessProbe:
        httpGet:
          path: /api/profile
          port: 3000
        initialDelaySeconds: 3
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Auth configuration
    auth:
      enabled: true
      image:
        tag: v2.143.0
      environment:
        API_EXTERNAL_URL: http://supabase.local
        GOTRUE_SITE_URL: http://supabase.local
        GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
        GOTRUE_MAILER_AUTOCONFIRM: "true"
        GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@example.com"
        GOTRUE_SMTP_HOST: "smtp.example.com"
        GOTRUE_SMTP_PORT: "587"
        GOTRUE_SMTP_SENDER_NAME: "your-mail@example.com"
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # REST API configuration
    rest:
      enabled: true
      image:
        tag: v12.0.1
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Realtime configuration
    realtime:
      enabled: true
      image:
        tag: v2.27.5
      livenessProbe:
        httpGet:
          path: /
          port: 4000
        initialDelaySeconds: 3
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Meta configuration
    meta:
      enabled: true
      image:
        tag: v0.80.0
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Storage configuration
    storage:
      enabled: true
      image:
        tag: v0.46.4
      livenessProbe:
        httpGet:
          path: /status
          port: 5000
        initialDelaySeconds: 3
      persistence:
        enabled: true
        size: 10Gi
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi
      # Use MinIO service from our cluster
      environment:
        STORAGE_BACKEND: s3
        GLOBAL_S3_PROTOCOL: http
        GLOBAL_S3_ENDPOINT: http://minio.minio.svc.cluster.local:9000
        GLOBAL_S3_FORCE_PATH_STYLE: true
        AWS_DEFAULT_REGION: stub

    # Image proxy configuration
    imgproxy:
      enabled: true
      image:
        tag: v3.8.0
      environment:
        IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      livenessProbe:
        exec:
          command:
            - imgproxy
            - health
        initialDelaySeconds: 3
      persistence:
        enabled: false
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Kong API Gateway configuration
    kong:
      enabled: true
      image:
        repository: kong
        tag: 2.8.1
      environment:
        KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
        KONG_LOG_LEVEL: info
      ingress:
        enabled: true
        className: "nginx"
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-staging
        tls:
          - secretName: supabase-tls
            hosts:
              - supabase.local
        hosts:
          - host: supabase.local
            paths:
              - path: /
                pathType: Prefix
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Analytics configuration
    analytics:
      enabled: true
      image:
        tag: 1.4.0
      livenessProbe:
        httpGet:
          path: /health
          port: 4000
        initialDelaySeconds: 3
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Vector configuration
    vector:
      enabled: true
      image:
        tag: 0.34.0-alpine
      livenessProbe:
        httpGet:
          path: /health
          port: 9001
        initialDelaySeconds: 3
      ## Vector requires logs from the control plane to function.
      ## This is normally stored in /var/log/pods
      ## Modify these values according to your environment.
      volumeMounts:
        - name: pod-logs
          mountPath: /var/log/pods
      volumes:
        - name: pod-logs
          hostPath:
            path: /var/log/pods
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi

    # Functions configuration
    functions:
      enabled: true
      image:
        tag: v1.41.2
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 512Mi
    
    # Disable MinIO since we're using the external MinIO deployment
    minio:
      enabled: false
