apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-values
  namespace: supabase
data:
  values.yaml: |
    # Default values for Supabase
    
    # Secret configuration
    secret:
      existingSecret: supabase-jwt
      existingSecretKeys:
        anonKey: anonKey
        serviceKey: serviceKey
        jwtSecret: jwtSecret
      
      # Other secrets - these should also be managed via external secrets
      smtp:
        existingSecret: supabase-smtp
        existingSecretKeys:
          username: username
          password: password
      
      dashboard:
        existingSecret: supabase-dashboard
        existingSecretKeys:
          username: username
          password: password
      
      db:
        existingSecret: supabase-db
        existingSecretKeys:
          username: username
          password: password
          database: database
          password_encoded: password_encoded
      
      analytics:
        existingSecret: supabase-analytics
        existingSecretKeys:
          apiKey: apiKey
      
      s3:
        existingSecret: supabase-s3
        existingSecretKeys:
          keyId: keyId
          accessKey: accessKey

    # PostgreSQL configuration
    db:
      enabled: true
      image:
        repository: supabase/postgres
        tag: 15.1.0.147
      livenessProbe:
        exec:
          command:
            - pg_isready
            - -U
            - postgres
        initialDelaySeconds: 3
      persistence:
        enabled: true
        size: 20Gi
      resources:
        limits:
          cpu: 500m
          memory: 800Mi
        requests:
          cpu: 100m
          memory: 400Mi

    # Studio configuration
    studio:
      enabled: true
      image:
        tag: 20240326-5e5586d
      environment:
        STUDIO_DEFAULT_ORGANIZATION: "My Organization"
        STUDIO_DEFAULT_PROJECT: "My Project"
        SUPABASE_PUBLIC_URL: http://supabase.local/
        NEXT_PUBLIC_ENABLE_LOGS: "true"
      livenessProbe:
        httpGet:
          path: /api/profile
          port: 3000
        initialDelaySeconds: 3
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 50m
          memory: 200Mi

    # Auth configuration
    auth:
      enabled: true
      image:
        tag: v2.143.0
      environment:
        API_EXTERNAL_URL: http://supabase.local
        GOTRUE_SITE_URL: http://supabase.local
        GOTRUE_EXTERNAL_EMAIL_ENABLED: "true"
        GOTRUE_MAILER_AUTOCONFIRM: "true"
        GOTRUE_SMTP_ADMIN_EMAIL: "your-mail@example.com"
        GOTRUE_SMTP_HOST: "smtp.example.com"
        GOTRUE_SMTP_PORT: "587"
        GOTRUE_SMTP_SENDER_NAME: "your-mail@example.com"
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 50m
          memory: 200Mi

    # REST API configuration
    rest:
      enabled: true
      image:
        tag: v12.0.1
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 50m
          memory: 200Mi

    # Realtime configuration
    realtime:
      enabled: false
      image:
        tag: v2.27.5
      livenessProbe:
        httpGet:
          path: /
          port: 4000
        initialDelaySeconds: 3
      resources:
        limits:
          cpu: 250m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 256Mi

    # Meta configuration
    meta:
      enabled: true
      image:
        tag: v0.80.0
      resources:
        limits:
          cpu: 250m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 256Mi

    # Storage configuration
    storage:
      enabled: true
      image:
        tag: v0.46.4
      livenessProbe:
        httpGet:
          path: /status
          port: 5000
        initialDelaySeconds: 3
      persistence:
        enabled: true
        size: 10Gi
      resources:
        limits:
          cpu: 250m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 256Mi
      # Use MinIO service from our cluster
      environment:
        STORAGE_BACKEND: s3
        GLOBAL_S3_PROTOCOL: http
        GLOBAL_S3_ENDPOINT: http://minio.minio.svc.cluster.local:9000
        GLOBAL_S3_FORCE_PATH_STYLE: true
        AWS_DEFAULT_REGION: stub

    # Image proxy configuration
    imgproxy:
      enabled: true
      image:
        tag: v3.8.0
      environment:
        IMGPROXY_ENABLE_WEBP_DETECTION: "true"
      livenessProbe:
        exec:
          command:
            - imgproxy
            - health
        initialDelaySeconds: 3
      persistence:
        enabled: false
      resources:
        limits:
          cpu: 250m
          memory: 512Mi
        requests:
          cpu: 50m
          memory: 256Mi

    # Kong API Gateway configuration
    kong:
      enabled: true
      image:
        repository: kong
        tag: 2.8.1
      environment:
        KONG_DECLARATIVE_CONFIG: /usr/local/kong/kong.yml
        KONG_LOG_LEVEL: info
      ingress:
        enabled: true
        className: "nginx"
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: letsencrypt-staging
        tls:
          - secretName: supabase-tls
            hosts:
              - supabase.local
        hosts:
          - host: supabase.local
            paths:
              - path: /
                pathType: Prefix
      resources:
        limits:
          cpu: 200m
          memory: 400Mi
        requests:
          cpu: 50m
          memory: 200Mi

    # Analytics configuration
    analytics:
      enabled: false

    # Vector configuration
    vector:
      enabled: false

    # Functions configuration
    functions:
      enabled: false

    # Disable MinIO since we're using the external MinIO deployment
    minio:
      enabled: false
