# Local Environment - Alerts Configuration for Flux
# This patch simplifies and relaxes alert thresholds for local development

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flux-alerts
  namespace: monitoring
  annotations:
    environment: "local"
spec:
  groups:
  - name: flux-system
    rules:
    # Increase the thresholds and durations for local development
    # to prevent unnecessary alerts during development
    - alert: FluxGitOperationFailed
      expr: sum by (namespace, name) (rate(gotk_source_git_operation_failed_total[10m])) > 0
      for: 15m  # Longer duration to reduce alert noise in local
      labels:
        severity: info  # Reduced severity for local development
      annotations:
        summary: "Git operation failed in {{ $labels.namespace }}/{{ $labels.name }}"
        description: "Git repository operations are failing. This is a development environment, so this alert is for informational purposes only."
        
    - alert: FluxReconciliationFailures
      expr: sum by (namespace, name) (rate(gotk_reconcile_error_total{controller=~"gitrepository|helmrepository|kustomization|helmrelease"}[10m])) > 0
      for: 20m  # Longer duration to reduce alert noise in local
      labels:
        severity: info  # Reduced severity for local development
      annotations:
        summary: "Flux reconciliation failures in {{ $labels.namespace }}/{{ $labels.name }}"
        description: "Flux reconciliation failures detected. This is a development environment, so this alert is for informational purposes only."
        
    # Disable the network latency alert for local development
    # as high latency is expected in local environments
    - alert: HighNetworkLatency
      expr: histogram_quantile(0.95, sum(rate(gotk_source_git_operation_duration_seconds_bucket[5m])) by (le, namespace, name)) > 30  # Higher threshold
      for: 30m  # Much longer duration to reduce alert noise in local
      labels:
        severity: info  # Reduced severity for local development
      annotations:
        summary: "High network latency for Git operations in {{ $labels.namespace }}/{{ $labels.name }}"
        description: "95th percentile of Git operation duration is high. This is a development environment, so this alert is for informational purposes only." 