apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base network configuration
resources:
  - ../../../network

# Common labels for all resources
commonLabels:
  environment: local
  tier: observability

# Common annotations for local environment
commonAnnotations:
  environment.type: "development"
  monitoring.enabled: "true"

# Apply the policy patches
patchesStrategicMerge:
  - flux-service-monitor-patch.yaml
  - flux-alerts-patch.yaml
  - flux-network-policy-patch.yaml 