apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/applications/supabase
commonLabels:
  environment: staging
  tier: application
commonAnnotations:
  monitoring.enabled: "true"
patchesStrategicMerge:
  - patches/helmrelease-patch.yaml 