apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/applications/supabase
commonLabels:
  environment: staging
  tier: application
commonAnnotations:
  monitoring.enabled: "true"
patchesStrategicMerge:
  - patches/helmrelease-patch.yaml

# Use transformers to handle namespaces
transformers:
- transformers/remove-namespace.yaml
- transformers/namespace-transformer.yaml 