---
# ENVIRONMENT-SPECIFIC: This IP address pool should be customized for each environment
# The addresses provided here are EXAMPLE values and should be overridden in environment overlays
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  # IP address range will be overridden in environment-specific overlays
  # Examples:
  # - Local: 192.168.0.240-192.168.0.250 (typical for minikube/kind/local environment)
  # - Staging: IP range from your staging network
  # - Production: IP range from your production network
  addresses:
  - 192.168.0.240-192.168.0.250
---
# ENVIRONMENT-SPECIFIC: The advertisement mode may differ by environment
# - Local/Staging typically use L2 mode (simple ARP/NDP)
# - Production might use BGP mode for more advanced setups
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advertisement
  namespace: metallb-system
spec:
  # Reference to the IP address pool
  ipAddressPools:
  - first-pool
  # Optional settings for specific environments:
  # interfaces:
  # - eth0
  # - bond0
  
  # Uncomment and change "first-pool" if using a different pool name
  # in your environment overlay 