---
# This is a HelmRelease Custom Resource for Flux v2 GitOps
# ENVIRONMENT-SPECIFIC: This may need adjustment based on your GitOps implementation
#
# Installation Options:
# 1. Flux v2: Use this HelmRelease as is (adjust sourceRef namespace if needed)
# 2. ArgoCD: Convert to Application CR or use helm chart directly
# 3. Manual: Use helm CLI with values
#    helm install metallb metallb/metallb --values values.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    # ENVIRONMENT-SPECIFIC: These annotations can be customized in environment overlays
    environment.config/description: "MetalLB for providing LoadBalancer services on bare-metal clusters"
spec:
  # ENVIRONMENT-SPECIFIC: Adjust interval based on environment
  # - local/dev: shorter intervals (5m)
  # - staging/prod: longer intervals (15m+)
  interval: 5m
  chart:
    spec:
      chart: metallb
      # ENVIRONMENT-SPECIFIC: Consider pinning to specific version in production
      version: "0.13.x"
      sourceRef:
        kind: HelmRepository
        name: metallb
        # ENVIRONMENT-SPECIFIC: Update namespace if needed for your GitOps setup
        namespace: flux-system
  # ENVIRONMENT-SPECIFIC: These values should be overridden in environment overlays
  values:
    # Always keep CRDs enabled (required for proper operation)
    crds:
      enabled: true
      
    # ENVIRONMENT-SPECIFIC: Configure speaker settings
    # - Speaker is a DaemonSet that advertises the services
    # - In production environments, consider resource limits
    speaker:
      # Production should consider setting tolerations to run on all nodes
      # tolerations:
      #   - effect: NoSchedule
      #     key: node-role.kubernetes.io/control-plane
      #     operator: Exists
      
      # ENVIRONMENT-SPECIFIC: Resource settings for different environments
      # resources:
      #   limits:
      #     cpu: 100m
      #     memory: 128Mi
      #   requests:
      #     cpu: 50m
      #     memory: 64Mi
    
    # ENVIRONMENT-SPECIFIC: Configure controller settings
    # - Controller is a Deployment that manages the configuration
    # - In production environments, consider resource limits and replicas
    controller:
      # ENVIRONMENT-SPECIFIC: Higher replicas for production
      # replicaCount: 1
      
      # ENVIRONMENT-SPECIFIC: Resource settings for different environments
      # resources:
      #   limits:
      #     cpu: 100m
      #     memory: 128Mi
      #   requests:
      #     cpu: 50m
      #     memory: 64Mi
      
    # ENVIRONMENT-SPECIFIC: Configure log level
    # - local/dev: debug for more verbose logging
    # - staging/prod: info or warning for less verbose logging
    # logLevel: info
    
    # ENVIRONMENT-SPECIFIC: Configure prometheus monitoring
    # - Typically enabled in staging/production
    # prometheus:
    #   serviceMonitor:
    #     enabled: true
    #     additionalLabels:
    #       release: prometheus
    
    # ENVIRONMENT-SPECIFIC: Additional advanced settings
    # - BGP settings if using BGP mode (typically in production)
    # - IPv6 settings if needed
    # - Other MetalLB specific settings 