apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base cert-manager configuration
resources:
- ../../../base/infrastructure/cert-manager

# Apply local-specific patches and configurations
patchesStrategicMerge:
- patches/cluster-issuers-patch.yaml

# Import local-specific values
configMapGenerator:
- name: cert-manager-values
  behavior: merge
  files:
  - values.yaml=helm/values.yaml 