apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-core-infra
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/staging/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 30m0s
  retryInterval: 2m0s
  wait: true
  healthChecks:
    # Core Infrastructure health checks
    - kind: Deployment
      name: cert-manager
      namespace: cert-manager
    - kind: Deployment
      name: sealed-secrets-controller
      namespace: sealed-secrets
    - kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
    # Stage 2 Infrastructure health checks
    - kind: Deployment
      name: vault
      namespace: vault
  force: true
  decryption:
    provider: sops
    secretRef:
      name: flux-system 