apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Using commonLabels for consistent labeling
commonLabels:
  environment: staging
  managed-by: kustomize

# Common annotations to be added to all resources
commonAnnotations:
  source: "gitops-infrastructure"

resources:
  - infrastructure/cert-manager
  - infrastructure/sealed-secrets
  - infrastructure/vault
  - infrastructure/gatekeeper

  # Applications components
  - applications

  # Infrastructure layer is fully added, now adding applications
  - infrastructure/ingress
  # Adding observability stack
  - observability/grafana
  - observability/prometheus
  - observability/loki 