apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Using commonLabels for consistent labeling
commonLabels:
  environment: staging
  managed-by: kustomize

# Common annotations to be added to all resources
commonAnnotations:
  source: "gitops-infrastructure"

resources:
  # Start with namespaces first to ensure they exist before other resources
  - infrastructure/namespaces

  # Core infrastructure components in dependency order
  - infrastructure/cert-manager
  - infrastructure/sealed-secrets
  - infrastructure/ingress
  - infrastructure/metallb

  # The following components are commented out until core components are stable
  # - infrastructure/vault
  # - infrastructure/gatekeeper
  # - applications
  # - observability/grafana
  # - observability/prometheus
  # - observability/loki 