apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus-stack
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: "44.x.x"
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  values:
    prometheus:
      prometheusSpec:
        retention: 7d
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 10Gi
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        thanos:
          objectStorageConfig:
            name: thanos-objstore-config
            key: objstore.yml
    thanosObjectStorageConfig:
      type: S3
      config:
        bucket: thanos
        endpoint: minio.minio-system:9000
        access_key: minioadmin  # In production, use a sealed secret
        secret_key: minioadmin  # In production, use a sealed secret
        insecure: true
    grafana:
      adminPassword: admin  # In production, use a sealed secret
      persistence:
        enabled: true
        size: 5Gi
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 300m
          memory: 256Mi
      additionalDataSources:
        - name: Loki
          type: loki
          url: http://loki-stack:3100
          access: proxy
        - name: Thanos
          type: prometheus
          url: http://prometheus-stack-thanos-query:9090
          access: proxy
    alertmanager:
      alertmanagerSpec:
        storage:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 2Gi
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
    # Service monitor configuration for other components
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelectorNilUsesHelmValues: false 