---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: supabase-analytics-secret
  namespace: supabase
spec:
  encryptedData:
    apiKey: AgARSGeDGq3AMdG4PEAkb6cyjx0Qt+13U1ri5vcw14Cqd9Q0gA8h7N+q6zxZ8JqlHHTAe+YxxunOFgfgpudzrTdps296oaHhuiRMVzN2sbnsfFqCjNFebSOUoensi6Kux73lAipTAc/9Vg3KPJvbmCRgvLbM6TJcVLK+TD5vJ0G7uLlF6wRKXBSsJmrG91dqSANPpE93D1aM7BtSSPaUttHhCHC6UlFShztTzNbrpIoXKb62HneYhDTYJxgFu1MEqX39YY9aUWxyzu41RBq99FinqUVDDf5lVfMwxQuTDIGT5wTTlE/H0FKPLM/OU2UBXl3vBUKWJQkOPUvNQgC5cwioodyL/RVyBYJ9wk+VhCKUSYqZPNFsPyMxQ2VZ38MEn1664yRzs9nogE+/uAGlXtDyAtBNQ40Kcd7bgawnojM38EYo4sVyVrqXamN3T/KQi9C0xAGPNCcQsD8W0HfLyZ4vzCv9fzZ8ZQDkg2KIMqIYDL195yLvU1lCqS9cI9rdClEPC7bRAJj14Kv3oHp2/XGTUiQmaeokg8nwo8j4IqxhgxWwLKTI3z2E5COeVPCCCgS74wX1ylq2YUSQdV+Q0sN7HWYkiLfSfoE5OKXExZ/55m6OL8xv1lR99Cby/MzjDmdVIGri2TLxx1OJNoMwwJ4CveCGd3gOXbAN3kwNw1NV1waCBw2l/iFT0AioTKHJ9Mx9VeyBsGBTFLvMVA/IXYGeQtinrhk1Wv/DRlqxsuM9TQ+PpjznhP0=
  template:
    metadata:
      creationTimestamp: null
      name: supabase-analytics-secret
      namespace: supabase
    type: Opaque
