---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: supabase-smtp
  namespace: supabase
spec:
  encryptedData:
    password: AgBEaqWnUZmtcsQNPM7pNGmQTVV6Tc43jkPSWuS4w/Ikr5KWuPcRoNNWY+0X6yxhPgJY+yJb2m5clZv5YLllCpIHM9Ekhwb8Gi2VlRMQKlWrf7um/89iI/BZe+mNQK0gVzjHkiM/9UsEq2BkUutVOPR7R5/u+qsOoTRXdrFMhdvkwcSyf49HJ6iqqWKO4oCALXleEj17TKaPdx7RtlvJMtdFzGegYaynoH1lyuGa3/wJi4pReKRO1F8AZP1rcsBO204FhlkOzsEJ6nAZ/o9vINDRm4BbnWjAqYsZnjnpnBj11JtUCGRNEWYyJDBbGbfokvRfcxGcgoQaTdYlEDwx7Nt3ROxuQnkmKsBQjhH2SZOvsggJkFw3aeaT/83dltX9VYiTyJge0VBhP50ZPDIlOVylb7QetIISrCpwKOuElz2W9253bmSA0LJm7QsJM3BoTKagvkPEl9vYMVw3Zuiv3/ews+93Q1adLnDq23K8bqDgPIMF88rS7Ezmo4YLlzDnv+hS2VdtlNldO7k1GY5uIuiXr2GW0AlqKemSABOWAbSuMbYeJopyYv7fqQoK71CfWYGMD0CiWdpXNeCX7jOJsbeLM8A9hvnMMIQaWHHd4FpDV6iwOVRGsAr3e+yokyRydO7esv/7fAjz39KTLJlWWZQREYl7/rDGjnw0a3e2nhJnhK0NujekphvdN3iassS9akG87TgmJ7E+gA==
    username: AgBvGYMSthCNdpUOEgte5YvLjmHfah0OisgYU5QUU94VRmwoUxbDVsehMfCSxjCas3PgqIPy0jmrs+MJL9/KbnKPKACWrz8z6A2dOPyYGGLZzUFXz3gfboqj0BPJDuqpzaSsD2eHpXrcL55KJGTkoyIElQptS3jXa18zUMyS5KDK52RX+pUgjbMfocxMQ3sX1Is97P9BhRPMzafzd0fSQJsHfo55KXo/atI5LF4prkXzehbNeh05s63VOoSCOCTD8Sn9eAaG++fXz7Zq4jn/Y62FhAkwd/DOuClwIDsOlfTJBoJvPDrtlFc4xVNY5QymUUTOoVZ7pm4fNTl45xAEJrRri9H5M+e6A+sMxag7S380meF3WzffmM0FMlod48DuTNcYKVweT6qtUjujoJ8FoQ0DxS0mnk2Rp6eUrPJpqYC6du0y6YxLj4WA5rhGaWYkJXZUGG+NGEDdsK7/wC84qcndh0deR9UOrNbKLbSZ33LurRVly7usfzAWtWZxCSjsY46Pdb3c75/6YT91TAMp5OzgChhV21BlTA+hgm7zLXjH1LvSIHl9jdSxEPNalO8H5lM2b8rNlHywNDqPBSz/WGMdjrlWw1iIsv5h+xCP3MQAV7lPljG3lMGF4kL/mMn/JVDifeiZO9QIAViUEjMXQ09y0Tfkp1iJANQH0gxKXM5E54gO9Cju3xBUl8ZuQVtDT5RhUU89CRUZNb9yXF4WbSt3
  template:
    metadata:
      creationTimestamp: null
      name: supabase-smtp
      namespace: supabase
    type: Opaque
