{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "supabase-analytics",
    "namespace": "supabase",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "supabase-analytics",
        "namespace": "supabase",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "apiKey": "AgAmAOMvRExVWvvfwVyAvkc0LZoNzuXhapfKaRaXpvgO0tlbxbXwpBcCptiE/Et/pLHdppcZ0HdimntP1vgX2vPUcrvMB+iB4BKiMVKg9MrKJMHm01tJhfygepI9yBVXiep4bnvVblun6gUcIsUfD6ym8SHuTyZoqd5fVh80vOrf21PlflVbUxj9XiXAwmq2zzCZ7k1q7Pb5BHQ1b1zOez+SFbap3srj2Q1Yy1d6+pwGe/7oIMlV7Rp3cAiQgL+YCsCtK1K2Cn9BQNN9xn9dTnVClcznYK5lk/TNVEyWX6f/xmBJc7Exxoy8CMG0I+0qPJTxi98amBqwNdS+V88N2EoO+3QtE/KbRc8D8k5A25/PVVX4kjKlIY5h+8zQ5kTNPGbEPUZPopRnwzSFBzXhbqz940W5x4CC7eYIaMX22SGFPtGqAQNIP2epZchLxYAzSvnoAWxJAV+Hx6VtUiexi2dKnkzzloTgAFfMmNC2fgoI8ezLoQ94C1R80+EkiPGHg/row98uHNANxFRSc3hv0WbEyYNv33BUo0P7DhBLJON+30uPJY3+3awpGgXcS50qdjwEK3rSG87KEAAxyHWQqi7wnfFGLaeK6ugqU6/3EY9TJRK4kIAXZ9C5N5R1Jtw9RqEoOOypxVFaYWcesfpILS36EkyBUnrwsmBgc6fy711TYmrYHadapcQXS0blu2n922JU0z24kXzoLTsHtv8zUlHqEbcetwoo"
    }
  }
}
