---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: supabase-s3
  namespace: supabase
spec:
  encryptedData:
    access_key: AgBnvJGeM43wSRI3/ddhGkAjp6jQ0Ugf6t914ksA7PakSIkzXNEvn7EOlZrR96OwUCLW0HWuRrQO2EDPCM63WkuRVNarVzK
    secret_key: AgBkI6TYxzELjB9QOZUu9G6ZuUZB9gq+FV5oYZAwvgixmLM7lpmoLLEGdoCpNHnwzrIqdZ8OjwBvJsWY8JmDL7SfXrkc
  template:
    metadata:
      creationTimestamp: null
      name: supabase-s3
      namespace: supabase
    type: Opaque
