{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "supabase-s3",
    "namespace": "supabase",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "supabase-s3",
        "namespace": "supabase",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "endpoint": "AgCH3Wkkhf+Kuzio+KqEVXemlp+KmfsMEiDValB3LeVXAgzR1cXpdYq4ZLhXmOdp6s/Q/8HRD/ZuOm6jL5QR7CNKNOAsvoxp0jnf2Ij14gpt+tK5PyzIYPiLhDjvbqGRoZ47wqwwxj1PqIqm6J2hfYpmGb7d7J/IH6z5l+UN2teXS3TB4GVaSJKwtRnVqj5stIHCH2OX+GBaoezHSER90gGJVjlEmS+qxVSrJmcmkFLkuICoW0B3bx7x6jFtyEpjEqMZorHLtqPo6motVmhD3gW1JHzaG1O7XBw6/D2IpNnvgqa+KjUbzMaZuUlR+0WKBZ/3KaNSiPB0Q4zHcFnWY6/khFChBpWS0jj0uI35YYjwMx/bstRs6tzTbicEw+4s5zgwRtnslMqMU+VeeG8yDXB7F+7xMCi+kCtrk/hNyXrb66hD3/sYJdvxFuDQeQWPTC+10a34Q8axkE43BGWoYIzdZSC8AtRB5iVbPPtR4R1ZkpF4O/KnWX20YaXwIlikXAlrSJskXEPncvUJciZdepozbFnP2RGwoAxISO+K1Cq64k/N4kMlZ/VDoPEaFAz/pGTMjePzfR1MX4LTEP1bA89cDvFLXScZhSPHkMXkFgK9GjqfHjj9/DoNi/NZgFz7QhQSYVyGSAFC9KqIXKsmXScF5qZkM3wNWP5UEuPBL0ibdmQfZcaS9LymJoJ42jcumGRLaXikOhWwqtepQK7F64FTazzN8o8hYvi4l13UIMQ0yu5GBo5oZHzmmw=="
    }
  }
}
