apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki
  namespace: loki
spec:
  # Staging environment specific settings
  interval: 15m  # Less frequent reconciliation for staging
  values:
    loki:
      # Scale for staging environment
      auth_enabled: false
      commonConfig:
        replication_factor: 1
      storage:
        type: filesystem
      compactor:
        shared_store: filesystem
        retention_enabled: true
        retention_delete_delay: 2h
        retention_delete_worker_count: 150
        compaction_interval: 10m
        working_directory: /var/loki/boltdb-shipper-compactor
        retention_provisional_delete_enabled: true
      limits_config:
        retention_period: 336h # 14 days
        enforce_metric_name: false
      storage_config:
        filesystem:
          directory: /var/loki/chunks
    # Resource configuration
    singleBinary:
      replicas: 1
      resources:
        requests:
          cpu: 200m
          memory: 512Mi
        limits:
          cpu: 500m
          memory: 1Gi
    gateway:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
        - host: loki.staging.boldorigins.io
          paths:
          - path: /
            pathType: Prefix
        tls:
        - hosts:
          - loki.staging.boldorigins.io
    # Persistence configuration
    persistence:
      enabled: true
      size: 50Gi
      storageClass: local-path
    serviceMonitor:
      enabled: true 