apiVersion: builtin
kind: PatchTransformer
metadata:
  name: remove-namespace
target:
  kind: Namespace
  name: security
patch: |
  $patch: delete
  apiVersion: v1
  kind: Namespace
  metadata:
    name: security
