apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: observability
type: Opaque
stringData:
  objstore.yml: |
    type: s3
    config:
      bucket: thanos
      endpoint: minio.minio-system:9000
      access_key: minioadmin  # In production, use a sealed secret
      secret_key: minioadmin  # In production, use a sealed secret
      insecure: true
      signature_version2: false 