apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
- namespace.yaml
# Reference to existing non-Helm resources
- crds.yaml
- cluster-issuers.yaml
# Reference to Helm-based resources
- helm/release.yaml

# Import values from the values file
configMapGenerator:
- name: cert-manager-values
  files:
  - values.yaml=helm/values.yaml 