apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base sealed-secrets configuration
resources:
- ../../../base/infrastructure/sealed-secrets

# Apply local-specific patches
patchesStrategicMerge:
- patches/deployment-patch.yaml 