---
# This is a HelmRelease Custom Resource Definition
# In a GitOps setup with Flux or ArgoCD, this would be managed by the GitOps controller
# For manual implementation, you would use: helm template gatekeeper/gatekeeper --values values.yaml | kubectl apply -f -
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
  annotations:
    # Force reconciliation to pick up the new RBAC settings
    reconcile.fluxcd.io/requestedAt: "2025-03-04T10:10:00Z"
spec:
  interval: 5m
  chart:
    spec:
      chart: gatekeeper
      version: 3.14.0
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
  values:
    # These values would be read from the values.yaml file
    replicas: 1
    auditInterval: 30
    logLevel: INFO
    # Explicitly enable RBAC to fix permission issues
    rbac:
      create: true
    # Configure service account
    serviceAccount:
      create: true
      name: "gatekeeper-admin"
    controllerManager:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    audit:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    webhook:
      enabled: true

---
# For reference, this is the HelmRepository CRD that would be used with Flux v2
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gatekeeper
  namespace: flux-system
spec:
  interval: 1h
  url: https://open-policy-agent.github.io/gatekeeper/charts 