# Values for Gatekeeper Helm chart
# Reference: https://github.com/open-policy-agent/gatekeeper/tree/master/charts/gatekeeper

# Number of replicas
replicas: 1

# Audit interval in seconds
auditInterval: 30

# Log level (INFO, DEBUG, WARNING, ERROR, CRITICAL)
logLevel: INFO

# RBAC configuration - explicitly enable to fix permission issues
rbac:
  create: true

# Service account configuration
serviceAccount:
  create: true
  name: "gatekeeper-admin"

# Fix permissions for the default service account
clusterRoles:
  - name: gatekeeper-manager-role
    rules:
      - apiGroups: ["*"]
        resources: ["*"]
        verbs: ["get", "list", "watch"]
      - apiGroups: ["admissionregistration.k8s.io"]
        resources: ["validatingwebhookconfigurations"]
        verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
      - apiGroups: [""]
        resources: ["secrets"]
        verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

# Controller Manager configuration
controllerManager:
  # Resource limits and requests
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

# Audit configuration
audit:
  # Resource limits and requests
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi

# Webhook configuration
webhook:
  enabled: true
  # Resource limits and requests are inherited from controllerManager

# Exempt namespaces from Gatekeeper webhook and constraints
exemptNamespaces:
  - kube-system
  - gatekeeper-system

# Enable validating webhook
validatingWebhook:
  enabled: true

# Enable cert rotation
certRotation:
  enabled: true

# Disable mutation feature
mutatingWebhook: false

# Custom annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8888"

# Metrics configuration
emitAdmissionEvents: true
emitAuditEvents: true
enableExternalData: true

# Validating webhook timeout
validatingWebhookTimeoutSeconds: 3

# PostInstall job (create default sync config)
postInstall:
  labelNamespace:
    enabled: false
  
# PostUpgrade job
postUpgrade:
  labelNamespace:
    enabled: false 