apiVersion: apps/v1
kind: Deployment
metadata:
  name: sealed-secrets-controller
  namespace: sealed-secrets
spec:
  replicas: 1  # Single replica for local development
  template:
    metadata:
      labels:
        name: sealed-secrets-controller
      annotations:
        dev.local/environment: "local"  # Local development annotation
    spec:
      containers:
      - name: sealed-secrets-controller
        # Development resource limits (lower than would be used in production)
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m" 