apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base sealed-secrets configuration
resources:
  - ../../../../base/infrastructure/sealed-secrets

# Common labels for all resources
commonLabels:
  environment: local
  tier: infrastructure

# Apply the values patch to the HelmRelease
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: sealed-secrets
        namespace: sealed-secrets
      spec:
        # Local environment specific settings
        interval: 1m  # More frequent reconciliation for development
        values:
          $patch: merge
          $(cat values-patch.yaml | indent 10)
    target:
      kind: HelmRelease
      name: sealed-secrets
      namespace: sealed-secrets 