apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-stack
  namespace: observability
spec:
  values:
    # Add local-specific values here
    resources:
      requests:
        memory: "64Mi"
        cpu: "50m"
      limits:
        memory: "128Mi"
        cpu: "100m"
    replicaCount: 1  # Single replica for local development
    # Configure grafana datasource settings to ensure Loki is not default
    grafana:
      enabled: false  # Keep disabled as we use Prometheus stack's Grafana
      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
          - name: Loki
            type: loki
            access: proxy
            url: "http://loki-stack:3100"
            version: 1
            isDefault: false
            jsonData: {}
