apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: observability
spec:
  interval: 15m
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: observability
  values:
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - grafana.staging.boldorigins.io
      tls:
        - hosts:
            - grafana.staging.boldorigins.io
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    persistence:
      enabled: true
      size: 5Gi
      storageClassName: local-path 