apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: jetstack
        namespace: cert-manager
  values:
    # Staging-specific values
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    # Configure the domain for certificates
    clusterIssuers:
      email: rodrigo.mourey@boldorigins.io
      defaultIssuer:
        name: letsencrypt-prod
        kind: ClusterIssuer
    # Enable leader election to prevent split-brain
    leaderElection:
      enabled: true 