apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base vault configuration
resources:
  - ../../../../base/infrastructure/vault

# Common labels for all resources
commonLabels:
  environment: staging
  tier: infrastructure

# Common annotations for staging
commonAnnotations:
  monitoring.enabled: "true"

# Generate the values ConfigMap with our staging values
configMapGenerator:
  - name: vault-values
    behavior: merge
    files:
      - values.yaml=values-patch.yaml

# Apply patches
patchesStrategicMerge:
  - ingress-patch.yaml

# Apply the Helm release patch
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: vault
        namespace: vault
        annotations:
          environment.config/description: "HashiCorp Vault for staging environment"
      spec:
        # Staging environment specific settings
        interval: 15m  # Less frequent reconciliation for staging
        chart:
          spec:
            version: "0.25.0"  # Pin to specific version for stability
        install:
          remediation:
            retries: 3
        upgrade:
          remediation:
            retries: 3
    target:
      kind: HelmRelease
      name: vault
      namespace: vault 