apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: example
  labels:
    app: example
    team: platform
    environment: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/role: "app-role"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "kv/data/database/config"
        vault.hashicorp.com/agent-inject-template-database-config.txt: |
          {{- with secret "kv/data/database/config" -}}
          export DB_USERNAME={{ .Data.data.username }}
          export DB_PASSWORD={{ .Data.data.password }}
          {{- end -}}
    spec:
      serviceAccountName: example-app
      containers:
      - name: app
        image: busybox:latest
        command: ["sh", "-c", "source /vault/secrets/database-config.txt && echo 'Connected to database as $DB_USERNAME' && echo 'Also using API key from sealed secret' && while true; do sleep 30; done"]
        env:
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: example-sealed-secret
              key: api-key
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          exec:
            command:
            - cat
            - /vault/secrets/database-config.txt
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          exec:
            command:
            - cat
            - /vault/secrets/database-config.txt
          initialDelaySeconds: 15
          periodSeconds: 20 