apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: example
resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - sealed-secret.yaml
  - vault-secret-example.yaml
  - network-policy.yaml
  - ingress.yaml

commonLabels:
  app: example-app
  part-of: example 