apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-secret-example
  namespace: example
  annotations:
    # NOTE: This is just for demonstration purposes.
    # In a real environment, you would use an external secrets operator like
    # kubernetes-external-secrets or external-secrets.io
    vault.hashicorp.com/secret-path: "kv/data/database/config"
    vault.hashicorp.com/secret-key: "username"
data:
  # This is a placeholder to demonstrate how Vault secrets could be used
  # In a real scenario, you would use an External Secrets Operator to fetch secrets from Vault
  example.txt: |
    This is an example of how to use Vault with an External Secrets Operator.
    
    Example usage:
    
    apiVersion: external-secrets.io/v1beta1
    kind: ExternalSecret
    metadata:
      name: vault-example
      namespace: example
    spec:
      refreshInterval: 1h
      secretStoreRef:
        name: vault-backend
        kind: ClusterSecretStore
      target:
        name: database-credentials
      data:
      - secretKey: username
        remoteRef:
          key: kv/data/database/config
          property: username
      - secretKey: password
        remoteRef:
          key: kv/data/database/config
          property: password 