apiVersion: v1
kind: Secret
metadata:
  name: tempo-s3-credentials
  namespace: observability
  # In a real environment, this would be managed by a secrets management solution
  # such as SealedSecrets, External Secrets, or HashiCorp Vault
type: Opaque
stringData:
  # These are placeholder values that should be replaced
  # IMPORTANT: Do not store real credentials in Git
  MINIO_ACCESS_KEY: "replace-with-real-access-key"
  MINIO_SECRET_KEY: "replace-with-real-secret-key" 