apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: observability
spec:
  # Staging environment values overrides
  values:
    tempo:
      # Staging environment: Use moderate resources for testing
      persistence:
        enabled: true
        size: 20Gi # Moderate storage for staging
      resources:
        requests:
          cpu: 200m     # Moderate CPU request for staging
          memory: 512Mi # Moderate memory request for staging
        limits:
          cpu: 500m     # Moderate CPU limit for staging
          memory: 1Gi   # Moderate memory limit for staging
      # Staging: Configure S3-compatible storage
      storage:
        trace:
          backend: s3
          s3:
            bucket: tempo-traces-staging
            endpoint: minio.minio.svc.cluster.local:9000
            access_key: ${MINIO_ACCESS_KEY}
            secret_key: ${MINIO_SECRET_KEY}
            insecure: true
          size: 20Gi
      # Staging: Retain data for 7 days
      retention: 168h
      # Enable metrics for monitoring in staging
      metricsGenerator:
        enabled: true
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi 