apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base metallb configuration
resources:
  - ../../../../base/infrastructure/metallb

# Common labels for all resources
commonLabels:
  environment: local
  tier: infrastructure

# Apply patches to update resources
patchesStrategicMerge:
  # Update IP address pool for local environment
  - ipaddresspool-patch.yaml

# Apply the values patch to the HelmRelease
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: metallb
        namespace: metallb-system
      spec:
        values:
          $patch: merge
          $(cat values-patch.yaml | indent 10)
    target:
      kind: HelmRelease
      name: metallb 