apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress
  - metallb
  - cert-manager
  - sealed-secrets
  # These will be added in stage 2
  # - vault
  # - security
  # - policy-engine
  # - minio
  # - gatekeeper
