apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress
  - metallb
  # Temporarily disabled problematic components
  # - vault
  # - security
  # - policy-engine
  # - minio
  # - supabase 