apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Stage 1 - Core Infrastructure Components
  - metallb
  - cert-manager
  - sealed-secrets
  - ingress
  
  # Stage 2 - Security and Storage Components
  - vault
  - security
  - policy-engine
  - minio
  - gatekeeper
