apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress
  - metallb
  # Disabled problematic components
  - vault
  - security
  # - policy-engine
  - minio
  # - supabase
  # - cert-manager
  # - gatekeeper
  - sealed-secrets 