apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress
  - metallb
  # Disabled problematic components
  - vault
  - security
  - policy-engine
  - minio
  # - supabase  # Removed - supabase should be in the applications directory
  - cert-manager
  - gatekeeper
  - sealed-secrets
