---
# This is a patch for the vault HelmRelease
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  # Staging environment specific settings
  interval: 15m  # Less frequent reconciliation for staging
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: vault
  values:
    server:
      resources:
        requests:
          memory: "256Mi"
          cpu: "100m"
        limits:
          memory: "512Mi"
          cpu: "200m"
      # Use one replica for staging
      ha:
        enabled: false
      # Enable service monitoring for Prometheus
      serviceMonitor:
        enabled: true
    # Enable ingress
    ui:
      enabled: true
      publishNotReadyAddresses: true
    # Enable TLS
    global:
      tlsDisable: false 