apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: security-suite
  namespace: security
spec:
  interval: 15m
  values:
    # Configure resource limits for security components
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
        
    # Enable scanning for vulnerabilities
    scanners:
      enabled: true
      schedule: "0 */6 * * *"  # Every 6 hours
      
    # Configure alert notifications
    alerts:
      enabled: true
      severity: "critical,high"
      
    # Enable security dashboards
    dashboards:
      enabled: true
      
    # Configure network policies 
    networkPolicies:
      enabled: true
      
    # Configure runtime security
    runtime:
      enabled: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "100m" 