apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: ingress-nginx
  values:
    controller:
      # Staging-specific values
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      # Use two replicas for staging for high availability
      replicaCount: 2
      # For VPS with public IP, use LoadBalancer
      service:
        type: LoadBalancer
      config:
        # Enable real IP detection for proper client IP logging
        use-forwarded-headers: "true"
        compute-full-forwarded-for: "true"
        use-proxy-protocol: "false"
        # Improve security
        server-tokens: "false"
        ssl-protocols: "TLSv1.2 TLSv1.3"
        # Increase timeouts for staging testing
        proxy-connect-timeout: "10"
        proxy-read-timeout: "120"
        proxy-send-timeout: "120" 