apiVersion: v1
kind: ConfigMap
metadata:
  name: tempo-grafana-datasource
  namespace: observability
  labels:
    grafana_datasource: "1"
data:
  tempo-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo:3100
      version: 1
      editable: true
      isDefault: false
      jsonData:
        httpMethod: GET
        tracesToLogs:
          datasourceUid: loki
          tags: ['instance', 'pod', 'namespace']
          spanEndTimeShift: "100ms"
          spanStartTimeShift: "-100ms"
          filterByTraceID: true
          filterBySpanID: true
          lokiSearch: true 