apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

# Reference the base configuration
resources:
  - ../../base
  - ../../config/grafana-datasource.yaml

# Apply local environment specific patches
patchesStrategicMerge:
  - values-patch.yaml

# Add environment-specific labels
commonLabels:
  environment: local
  app.kubernetes.io/environment: local 