---
# Production Environment: IP Address Pool Configuration
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  # Production environment IP range - must be dedicated to production services
  # This range should be allocated specifically for LoadBalancer services
  addresses:
  - 10.0.0.100-10.0.0.200  # PLACEHOLDER: Adjust based on your production network
  
  # Optional: Auto-assign allows MetalLB to automatically assign IPs from this pool
  autoAssign: true

---
# Optional: BGP Advertisement for production
# This replaces the L2Advertisement in the base configuration
apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: bgp-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
  
  # Optional: Advanced BGP settings for production
  # aggregationLength: 32
  # localPref: 100
  # communities:
  # - 65535:65281

---
# Production BGP peer configuration
# Uncomment and adjust parameters according to your network setup
# apiVersion: metallb.io/v1beta2
# kind: BGPPeer
# metadata:
#   name: router-1
#   namespace: metallb-system
# spec:
#   myASN: 64500
#   peerASN: 64501
#   peerAddress: 10.0.0.1 