apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base metallb configuration
resources:
  - ../../../../base/infrastructure/metallb

# Common labels for all resources
commonLabels:
  environment: production
  tier: infrastructure
  criticality: high

# Production-specific annotations
commonAnnotations:
  production-ready: "true"
  backup-policy: "daily"
  security-tier: "critical"
  monitoring.enabled: "true"

# Apply patches to update resources
patchesStrategicMerge:
  # Update IP address pool for production environment
  - ipaddresspool-patch.yaml

# Apply the values patch to the HelmRelease
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: metallb
        namespace: metallb-system
        annotations:
          fluxcd.io/automated: "false"  # Disable automated updates in production
      spec:
        # Longer reconciliation interval for production
        interval: 30m
        # Specific chart version for production stability
        chart:
          spec:
            version: "0.13.11"  # Pin to specific version for production
        # Add Install/Upgrade strategies for production
        install:
          remediation:
            retries: 5
        upgrade:
          remediation:
            retries: 5
        values:
          $patch: merge
          $(cat values-patch.yaml | indent 10)
    target:
      kind: HelmRelease
      name: metallb 