apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../clusters/base/infrastructure/prometheus
commonLabels:
  environment: staging
  tier: infrastructure
commonAnnotations:
  monitoring.enabled: "true"
patchesStrategicMerge:
  - patches/helmrelease-patch.yaml 