apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base ingress configuration
resources:
  - ../../../../base/infrastructure/ingress

# Common labels for all resources
commonLabels:
  environment: staging
  tier: infrastructure

# Common annotations for all resources
commonAnnotations:
  monitoring.enabled: "true"

# Apply the values patch to the HelmRelease
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      metadata:
        name: ingress-nginx
        namespace: ingress-nginx
      spec:
        # Longer reconciliation interval for staging
        interval: 15m
        values:
          $patch: merge
          $(cat values-patch.yaml | indent 10)
    target:
      kind: HelmRelease
      name: ingress-nginx 