apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

resources:
- namespace.yaml
- ingress.yaml
# Reference to Helm-based resources
- helm/release.yaml

# Import values from the values file
configMapGenerator:
- name: vault-values
  files:
  - values.yaml=helm/values.yaml 