apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  # Staging environment specific settings
  interval: 15m  # Less frequent reconciliation for staging
  values:
    replicas: 1
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "200m"
    # Configure audit
    audit:
      resources:
        requests:
          memory: "128Mi"
          cpu: "50m"
        limits:
          memory: "256Mi"
          cpu: "100m"
    # Enable metrics
    enableExternalPrometheusMetrics: true
    # Set appropriate log level
    logLevel: INFO
    # Enable mutations and validations
    mutations:
      enabled: true
    validatingWebhookTimeoutSeconds: 3 