# Staging Environment - Balanced Resources Configuration for Prometheus
# This patch provides moderate resource allocation for staging environments

prometheus:
  prometheusSpec:
    # Moderate retention time for staging
    retention: 7d
    # Two replicas for better availability in staging
    replicas: 2
    # Moderate resource requirements
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
      limits:
        memory: 2Gi
        cpu: 1000m
    # Enable persistent storage for staging
    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
    # Standard scrape interval
    scrapeInterval: 1m
    # Enable Thanos sidecar for object storage integration
    thanos:
      objectStorageConfig:
        name: thanos-objstore
        key: objstore.yml

# Enable Alertmanager with moderate resources
alertmanager:
  enabled: true
  alertmanagerSpec:
    replicas: 2
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m

# Disable Grafana as it's deployed separately
grafana:
  enabled: false

# Moderate resources for kube-state-metrics
kubeStateMetrics:
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 256Mi
      cpu: 200m

# Moderate resources for node-exporter
nodeExporter:
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m 