apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base ingress configuration
resources:
- ../../../base/infrastructure/ingress

# Apply local-specific patches
patchesStrategicMerge:
- patches/helmrelease-patch.yaml 