apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: tempo
spec:
  # Staging environment specific settings
  interval: 15m  # Less frequent reconciliation for staging
  values:
    # Configure appropriate resources for staging
    tempo:
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 200m
          memory: 512Mi
      # Configure storage for staging
      storage:
        trace:
          size: 10Gi
    # Configure service monitoring
    serviceMonitor:
      enabled: true
    # Configure gateway
    gateway:
      enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: tempo.staging.boldorigins.io
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - tempo.staging.boldorigins.io 