apiVersion: v1
kind: Secret
metadata:
  name: supabase-jwt
  namespace: supabase
type: Opaque
stringData:
  anonKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJhbm9uIiwiZXhwIjoxOTg3NjM0MDAwfQ.SupbFbSRSOA5Yx7ERcJwJ0UxTZmq_mBVp7VQrLuYgdw
  serviceKey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJvbGUiOiJzZXJ2aWNlX3JvbGUiLCJleHAiOjE5ODc2MzQwMDB9.rB3yjhBaXrUB2nMCw40kMSZwU5F03H5-0CQ-_7uX-MY
  jwtSecret: your-super-secure-jwt-secret-key-at-least-32-chars 