# Values for Sealed Secrets Helm chart
# Reference: https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets

# Use custom name
fullnameOverride: sealed-secrets

# Namespace to deploy the controller
namespace: sealed-secrets

# Service account configuration
serviceAccount:
  create: true
  name: sealed-secrets-controller
  annotations: {}

# Secret name for the controller key
secretName: sealed-secrets-key

# Resource limits and requests
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

# Controller settings
controller:
  # Release specific configuration
  image:
    repository: bitnami/sealed-secrets-controller
    tag: v0.24.5
    pullPolicy: IfNotPresent
  
  # Command line arguments - removed --key-label flag which was causing crashes
  command:
    - controller
  args:
    - --key-prefix=sealed-secrets-key
    - --update-status

# Pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

# Service configuration
service:
  type: ClusterIP
  port: 8080

# Security context
securityContext:
  fsGroup: 65534
  runAsUser: 1001

# Ingress (disabled by default)
ingress:
  enabled: false 