# Values for Sealed Secrets Helm chart
# Reference: https://github.com/bitnami-labs/sealed-secrets/tree/main/helm/sealed-secrets

# NOTE: There was an issue with the v0.24.5 controller:
# 1. The --key-label flag does not exist in this version
# 2. The service account needs to be explicitly set in the deployment
# These issues are addressed in the configuration below.

# Use custom name
fullnameOverride: sealed-secrets-controller

# Namespace to deploy the controller
namespace: sealed-secrets

# Service account configuration
serviceAccount:
  create: true
  name: sealed-secrets-controller
  annotations: {}

# Secret name for the controller key
secretName: sealed-secrets-key

# Resource limits and requests
resources:
  requests:
    memory: "64Mi"
    cpu: "50m"
  limits:
    memory: "128Mi"
    cpu: "100m"

# Controller settings
controller:
  # Release specific configuration
  image:
    repository: bitnami/sealed-secrets-controller
    tag: v0.24.5
    pullPolicy: IfNotPresent
  
  # UPDATED: Fixed the args format for Helm compatibility
  args:
    - --update-status
    - --key-prefix=sealed-secrets-key
    - --log-level=debug

# Pod annotations
podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8080"

# Service configuration
service:
  type: ClusterIP
  port: 8080

# Security context
securityContext:
  fsGroup: 65534
  runAsUser: 1001

# Ingress (disabled by default)
ingress:
  enabled: false 