apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base policies configuration
resources:
  - ../../../policies
  # Add production-specific resources
  - pod-security-policy.yaml

# Common labels for all resources
commonLabels:
  environment: production
  tier: policies
  criticality: high

# Common annotations for production environment
commonAnnotations:
  environment.type: "production"
  policies.enforcement: "strict"
  security-tier: "critical"

# Apply the policy patches
patchesStrategicMerge:
  - require-probes-patch.yaml 