---
# This is a HelmRelease Custom Resource Definition
# In a GitOps setup with Flux or ArgoCD, this would be managed by the GitOps controller
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: example-app
  namespace: example
spec:
  interval: 5m
  # For custom applications, we would define a chart in the GitOps repository
  chart:
    spec:
      chart: ./charts/example-app
      sourceRef:
        kind: GitRepository
        name: gitops-infrastructure
        namespace: flux-system
  values:
    # These values would be read from the values.yaml file
    replicaCount: 1
    image:
      repository: busybox
      tag: latest
      pullPolicy: IfNotPresent
    
    serviceAccount:
      create: true
      name: example-app
    
    # Vault integration
    vault:
      enabled: true
      role: app-role
      secretPath: kv/data/database/config
    
    # Sealed Secret integration
    sealedSecrets:
      enabled: true
      secretName: example-sealed-secret
    
    resources:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "200m"
    
    service:
      type: ClusterIP
      port: 80
      targetPort: 8080 