apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base grafana configuration
resources:
  - ../../../grafana

# Common labels for all resources
commonLabels:
  environment: staging
  tier: observability

# Common annotations for staging environment
commonAnnotations:
  environment.type: "staging"
  monitoring.enabled: "true"
  backup.enabled: "true"

# Merge our values with the base values
configMapGenerator:
  - name: grafana-values
    behavior: merge
    files:
      - values.yaml=values-patch.yaml

# Create secrets for staging environment
secretGenerator:
  - name: grafana-admin-credentials
    type: Opaque
    literals:
      - password=StrongStagingPassword123!
  - name: grafana-smtp-credentials
    type: Opaque
    literals:
      - password=StagingSmtpPassword456! 