apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: "0.23.x"
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    global:
      tlsDisable: false
    server:
      # In a real production environment, dev mode should be disabled
      # For this setup, we keep it enabled for simplicity
      dev:
        enabled: true
      standalone:
        enabled: true  # For production, use HA mode
      dataStorage:
        enabled: true
        size: 10Gi  # Increased size for production use
        storageClass: null
        accessMode: ReadWriteOnce
      service:
        enabled: true
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          # Use self-signed for local development
          cert-manager.io/cluster-issuer: "selfsigned-cluster-issuer"
          # For staging environment
          # cert-manager.io/cluster-issuer: "letsencrypt-staging"
          # For production
          # cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          nginx.ingress.kubernetes.io/ssl-passthrough: "true"
        hosts:
          - host: vault.local
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: vault-tls
            hosts:
              - vault.local
      # Add common Vault configurations
      extraEnvironmentVars:
        VAULT_ADDR: "https://127.0.0.1:8200"
        VAULT_SKIP_VERIFY: "true"
      resources:
        requests:
          memory: 256Mi
          cpu: 250m
        limits:
          memory: 512Mi
          cpu: 500m
    ui:
      enabled: true
      serviceType: ClusterIP
      externalPort: 8200
    # Enable audit logs
    auditStorage:
      enabled: true
      size: 5Gi
    # Configure Vault to use Kubernetes auth method by default
    injector:
      enabled: true
      replicas: 1
      resources:
        requests:
          memory: 128Mi
          cpu: 100m
        limits:
          memory: 256Mi
          cpu: 250m
      # Configure the Vault Agent Injector
      authPath: "auth/kubernetes" 