apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bucket-setup
  namespace: minio-system
  annotations:
    # This ensures the job is recreated when config changes
    kustomize.toolkit.fluxcd.io/prune: "true"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mc
        image: minio/mc:latest
        command:
        - /bin/sh
        - -c
        - |
          # Wait for MinIO to be ready
          echo "Waiting for MinIO server to be ready..."
          until mc alias set myminio http://minio:9000 minioadmin minioadmin; do
            sleep 5
          done
          
          # Create required buckets if they don't exist
          for BUCKET in loki thanos prometheus tempo logs backups; do
            if mc ls myminio/$BUCKET > /dev/null 2>&1; then
              echo "Bucket '$BUCKET' already exists, skipping creation."
            else
              echo "Creating bucket '$BUCKET'..."
              mc mb myminio/$BUCKET
              mc policy set public myminio/$BUCKET
            fi
          done
          
          # Configure retention policies for logs and metrics
          echo "Setting retention policy for log buckets..."
          mc ilm add --expiry-days 30 myminio/logs
          mc ilm add --expiry-days 30 myminio/loki
          
          echo "Bucket setup completed!"
      initContainers:
      - name: wait-for-minio
        image: busybox
        command:
        - sh
        - -c
        - |
          until wget --spider -q http://minio:9000/minio/health/ready; do
            echo "Waiting for MinIO to be ready..."
            sleep 10
          done 