apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supabase-s3
  namespace: supabase
spec:
  # This is a template file - actual values should be sealed for each environment
  # using the appropriate public key
  encryptedData:
    # S3 storage credentials as expected by values.yaml
    keyId: <SEALED_S3_KEY_ID>
    accessKey: <SEALED_S3_ACCESS_KEY>
  template:
    metadata:
      name: supabase-s3
      namespace: supabase
    type: Opaque 