apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supabase-analytics
  namespace: supabase
spec:
  # This is a template file - actual values should be sealed for each environment
  # using the appropriate public key
  encryptedData:
    # Analytics configuration as expected by values.yaml
    apiKey: <SEALED_ANALYTICS_API_KEY>
  template:
    metadata:
      name: supabase-analytics
      namespace: supabase
    type: Opaque 