apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supabase-jwt
  namespace: supabase
spec:
  # This is a template file - actual values should be sealed for each environment
  # using the appropriate public key
  encryptedData:
    # JWT configuration and API keys as required by values.yaml
    anonKey: <SEALED_ANON_KEY>
    serviceKey: <SEALED_SERVICE_KEY>
    jwtSecret: <SEALED_JWT_SECRET>
  template:
    metadata:
      name: supabase-jwt
      namespace: supabase
    type: Opaque 