apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supabase-smtp
  namespace: supabase
spec:
  # This is a template file - actual values should be sealed for each environment
  # using the appropriate public key
  encryptedData:
    # SMTP configuration as expected by values.yaml
    username: <SEALED_SMTP_USERNAME>
    password: <SEALED_SMTP_PASSWORD>
  template:
    metadata:
      name: supabase-smtp
      namespace: supabase
    type: Opaque 