apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: supabase-db
  namespace: supabase
spec:
  # This is a template file - actual values should be sealed for each environment
  # using the appropriate public key
  encryptedData:
    # Database credentials as expected by values.yaml
    username: <SEALED_DB_USERNAME>
    password: <SEALED_DB_PASSWORD>
    database: <SEALED_DB_NAME>
    password_encoded: <SEALED_DB_PASSWORD_ENCODED>
  template:
    metadata:
      name: supabase-db
      namespace: supabase
    type: Opaque 