apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-cluster-issuer
  annotations:
    # This self-signed issuer is suitable for all environments
    # Primarily used for internal or development certificates
    environment.config/description: "Self-signed issuer for internal certificates"
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  annotations:
    # The staging issuer should be used for testing in non-production environments
    # It doesn't have rate limits but certificates won't be trusted by browsers
    environment.config/description: "Let's Encrypt staging issuer for testing"
    environment.config/environments: "local,staging"
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    # ENVIRONMENT-SPECIFIC: Override this email address in your environment overlay
    # Production environments should use a monitored email address
    email: placeholder@example.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - http01:
          ingress:
            class: nginx
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  annotations:
    # The production issuer should only be used in staging/production environments
    # Be aware of rate limits: https://letsencrypt.org/docs/rate-limits/
    environment.config/description: "Let's Encrypt production issuer"
    environment.config/environments: "staging,production"
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    # ENVIRONMENT-SPECIFIC: Override this email address in your environment overlay
    # Production environments should use a monitored email address
    email: placeholder@example.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx
