apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  - namespace.yaml
  - crds.yaml
  - cluster-issuers.yaml
  - helm/release.yaml

# Import values from the values file
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=helm/values.yaml
