apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This namespace transformation only applies to resources without explicitly set namespaces
namespace: cert-manager

resources:
  - namespace.yaml
  - crds.yaml
  - cluster-issuers.yaml
  - helm/release.yaml
  # Important: This file contains resources with explicit namespace: flux-system
  - flux-system-resources.yaml

# Import values from the values file
configMapGenerator:
  - name: cert-manager-values
    files:
      - values.yaml=helm/values.yaml
