{{- if .Values.sealedSecrets.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ include "example-app.fullname" . }}-sealed-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "example-app.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{- if .Values.sealedSecrets.data }}
    {{- range $key, $value := .Values.sealedSecrets.data }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- else }}
    # This is a placeholder. In a real scenario, you would use kubeseal to encrypt your secrets
    # Example:
    # api-key: AgBy8hCF8...encrypted-data...
    # api-secret: AgBy8hCF8...encrypted-data...
    {{- end }}
{{- end }} 