apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base observability common configuration
resources:
  - ../../../../base/observability/common

# Common labels for all resources
commonLabels:
  environment: local
  tier: observability

# Apply the sources patches
patchesStrategicMerge:
  - sources-patch.yaml 