apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: verification

resources:
- namespace.yaml
- rbac.yaml
- checks/infrastructure-verification.yaml
- checks/application-verification.yaml
- dashboard/configmap.yaml
- dashboard/deployment.yaml
- dashboard/service.yaml
- dashboard/ingress.yaml
