apiVersion: v1
kind: ServiceAccount
metadata:
  name: verification-sa
  namespace: verification
  labels:
    app.kubernetes.io/part-of: gitops-verification
    app.kubernetes.io/managed-by: flux
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: verification-role
  labels:
    app.kubernetes.io/part-of: gitops-verification
    app.kubernetes.io/managed-by: flux
rules:
- apiGroups: [""]
  resources: ["pods", "services", "namespaces", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "update", "patch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["cert-manager.io"]
  resources: ["certificates", "issuers", "clusterissuers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["bitnami.com"]
  resources: ["sealedsecrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["helm.toolkit.fluxcd.io"]
  resources: ["helmreleases"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: verification-role-binding
  labels:
    app.kubernetes.io/part-of: gitops-verification
    app.kubernetes.io/managed-by: flux
subjects:
- kind: ServiceAccount
  name: verification-sa
  namespace: verification
roleRef:
  kind: ClusterRole
  name: verification-role
  apiGroup: rbac.authorization.k8s.io
