# ENVIRONMENT-SPECIFIC: Helm Repositories for Observability Stack
# These repositories provide the Helm charts for the observability components
# These configurations are generally consistent across environments

---
# Grafana Helm Repository
# ENVIRONMENT-SPECIFIC: Repository configurations may be centralized or environment-specific
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system
  # ENVIRONMENT-SPECIFIC: Add environment-specific annotations if needed
  # annotations:
  #   environment: base
spec:
  # ENVIRONMENT-SPECIFIC: Sync interval may differ by environment
  # - local/dev: can use shorter intervals for faster testing
  # - production: longer intervals to reduce API load
  interval: 1h
  url: https://grafana.github.io/helm-charts

---
# Prometheus Community Helm Repository
# ENVIRONMENT-SPECIFIC: Repository configurations may be centralized or environment-specific
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: prometheus-community
  namespace: flux-system
  # ENVIRONMENT-SPECIFIC: Add environment-specific annotations if needed
  # annotations:
  #   environment: base
spec:
  # ENVIRONMENT-SPECIFIC: Sync interval may differ by environment
  interval: 1h
  url: https://prometheus-community.github.io/helm-charts 