apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base cert-manager configuration
resources:
- ../../../../base/infrastructure/cert-manager
- issuer/letsencrypt-staging.yaml
- issuer/letsencrypt-prod.yaml

# Apply staging-specific patches
patchesStrategicMerge:
- patches/helmrelease-patch.yaml 