apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base tempo configuration
resources:
- ../../../base/observability/tempo
- config/grafana-datasource.yaml

# Apply local-specific patches
patchesStrategicMerge:
- patches/values-patch.yaml

# Add local-specific labels
labels:
- pairs:
    environment: local
    app.kubernetes.io/environment: local
  includeSelectors: true 