apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base minio configuration
resources:
- ../../../../clusters/base/infrastructure/minio

# Common labels for all resources
commonLabels:
  environment: staging
  tier: infrastructure

# Common annotations for staging
commonAnnotations:
  monitoring.enabled: "true"

# Apply staging-specific patches
patchesStrategicMerge:
- patches/helmrelease-patch.yaml

# Use transformers to exclude the namespace
transformers:
- transformers/remove-namespace.yaml 