apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base grafana configuration
resources:
  - ../../../grafana

# Common labels for all resources
commonLabels:
  environment: local
  tier: observability

# Common annotations for local environment
commonAnnotations:
  environment.type: "development"
  monitoring.enabled: "true"

# Merge our values with the base values
configMapGenerator:
  - name: grafana-values
    behavior: merge
    files:
      - values.yaml=values-patch.yaml 