# Local Environment - Minimal Resources Configuration for Grafana
# This patch reduces resource usage for local development environments

# Single replica for local development
replicas: 1

# Reduced resource requirements for local development
resources:
  requests:
    memory: 128Mi
    cpu: 50m
  limits:
    memory: 256Mi
    cpu: 100m

# Disable persistence for local development
persistence:
  enabled: false

# Admin user configuration for easy local access
adminUser: admin
adminPassword: admin

# Simplified service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration for local development
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - grafana.local.cluster.local

# Disable SMTP for local development
smtp:
  enabled: false

# Simplified datasources for local development
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server.observability.svc.cluster.local
        access: proxy
        isDefault: true

# Disable Grafana Enterprise features
enterprise:
  enabled: false 