apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-core-infra
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/local/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  retryInterval: 2m0s
  wait: true
  healthChecks:
    - kind: Deployment
      name: vault
      namespace: vault
  force: true
  decryption:
    provider: sops
    secretRef:
      name: flux-system
