apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: local-core-infra-stage2
  namespace: flux-system
spec:
  dependsOn:
    - name: local-core-infra
  interval: 10m0s
  path: ./clusters/local/infrastructure-stage2
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  retryInterval: 2m0s
  wait: true 