apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Using commonLabels since there's an issue with the labels format
commonLabels:
  environment: local
  managed-by: kustomize

# Common annotations to be added to all resources
commonAnnotations:
  source: "gitops-infrastructure"

resources:
- infrastructure/cert-manager
- infrastructure/sealed-secrets
# Temporarily commenting out vault to troubleshoot
# - infrastructure/vault
- infrastructure/gatekeeper
- infrastructure/minio
# Temporarily commenting out supabase due to secrets directory issues
# - infrastructure/supabase
# Now that infrastructure is set up, let's enable applications
# Temporarily excluding example app due to label conflict with existing deployment
# - apps/example
# MinIO moved to infrastructure directory
# - apps/minio

# Infrastructure layer is fully added, now adding applications
- infrastructure/ingress
- infrastructure/metallb 