apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common labels to be added to all resources
commonLabels:
  environment: local
  managed-by: kustomize

# Common annotations to be added to all resources
commonAnnotations:
  source: "gitops-infrastructure"

resources:
- infrastructure/cert-manager
# Temporarily commenting out other resources until we resolve the namespace issues
# - infrastructure/sealed-secrets
# - infrastructure/vault
# - infrastructure/gatekeeper
# - apps/example
# - apps/minio

# Simplified approach - start with cert-manager only, then add others incrementally 