apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Using commonLabels since there's an issue with the labels format
commonLabels:
  environment: local
  managed-by: kustomize

# Common annotations to be added to all resources
commonAnnotations:
  source: "gitops-infrastructure"

resources:
- infrastructure/cert-manager
- infrastructure/sealed-secrets
# Temporarily commenting out other resources until we resolve the namespace issues
# - infrastructure/vault
# - infrastructure/gatekeeper
# - apps/example
# - apps/minio

# Adding components incrementally - cert-manager and sealed-secrets added 