apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Using commonLabels since there's an issue with the labels format
commonLabels:
  environment: local
  managed-by: kustomize

# Common annotations to be added to all resources
commonAnnotations:
  source: "gitops-infrastructure"

resources:
  - infrastructure/cert-manager
  - infrastructure/sealed-secrets
  - infrastructure/vault
  - infrastructure/gatekeeper
  - infrastructure/minio

  # Applications components
  - applications

  # Infrastructure layer is fully added, now adding applications
  - infrastructure/ingress
  - infrastructure/metallb
  # Adding observability stack
  - observability/grafana
  - observability/prometheus
  - monitoring-kustomization.yaml
  - observability/loki
