apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Using commonLabels since there's an issue with the labels format
commonLabels:
  environment: local
  managed-by: kustomize

# Common annotations to be added to all resources
commonAnnotations:
  source: "gitops-infrastructure"

resources:
- infrastructure/cert-manager
- infrastructure/sealed-secrets
- infrastructure/vault
- infrastructure/gatekeeper
# Temporarily commenting out app resources until all infrastructure is working
# - apps/example
# - apps/minio

# Adding components incrementally - infrastructure layer is fully added 