apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: supabase-production

bases:
  - ../platform-config
  - ./infrastructure

# Using commonLabels since there's an issue with the labels format
commonLabels:
  environment: production
  managed-by: kustomize

# Common annotations to be added to all resources
commonAnnotations:
  source: "gitops-infrastructure"

resources:
- infrastructure/cert-manager
- infrastructure/sealed-secrets
- infrastructure/vault
- infrastructure/gatekeeper
- infrastructure/minio
- infrastructure/supabase
- infrastructure/ingress
- infrastructure/metallb
- infrastructure/policy-engine
- infrastructure/security
- observability
- policies
# Add your applications here
# - apps/example 