apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base vault configuration
resources:
  - ../../../../base/infrastructure/vault

# Common labels for all resources
commonLabels:
  environment: production
  tier: infrastructure
  criticality: high

# Common annotations for production
commonAnnotations:
  production-ready: "true"
  backup-policy: "daily"
  security-tier: "critical"
  monitoring.enabled: "true"

# Generate the values ConfigMap with our production values
configMapGenerator:
  - name: vault-values
    behavior: merge
    files:
      - values.yaml=values-patch.yaml

# Apply patches
patchesStrategicMerge:
  - ingress-patch.yaml

# Apply the Helm release patch
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: vault
        namespace: vault
        annotations:
          fluxcd.io/automated: "false"  # Disable automated updates in production
          environment.config/description: "HashiCorp Vault for production environment"
      spec:
        # Production environment specific settings
        interval: 30m  # Less frequent reconciliation for production
        chart:
          spec:
            version: "0.25.0"  # Pin to specific version for production stability
        # Add Install/Upgrade strategies for production
        install:
          remediation:
            retries: 5
        upgrade:
          remediation:
            retries: 5
            remediateLastFailure: true
          crds: Skip
          # Production-specific upgrade strategy
          force: false
    target:
      kind: HelmRelease
      name: vault
      namespace: vault
      
  # Additional customizations for vault deployment
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: vault
        namespace: vault
      spec:
        template:
          metadata:
            annotations:
              critical-component: "true"
              cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
          spec:
            securityContext:
              runAsNonRoot: true
              runAsUser: 100
              fsGroup: 1000
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchLabels:
                      app.kubernetes.io/name: vault
                  topologyKey: "kubernetes.io/hostname"
    target:
      kind: Deployment
      name: vault
      namespace: vault 