---
# This is a HelmRelease Custom Resource Definition
# In a GitOps setup with Flux or ArgoCD, this would be managed by the GitOps controller
# For manual implementation, you would use: helm template hashicorp/vault --values values.yaml | kubectl apply -f -
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 5m
  chart:
    spec:
      chart: vault
      version: 0.25.0
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  values:
    # These values would be read from the values.yaml file
    server:
      dev:
        enabled: true
        devRootToken: "root"
      service:
        enabled: true
        type: ClusterIP
      dataStorage:
        enabled: false
      standalone:
        enabled: true
      resources:
        requests:
          memory: "128Mi"
          cpu: "100m"
        limits:
          memory: "256Mi"
          cpu: "200m"
      serviceAccount:
        create: true
        name: vault

---
# For reference, this is the HelmRepository CRD that would be used with Flux v2
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: hashicorp
  namespace: flux-system
spec:
  interval: 1h
  url: https://helm.releases.hashicorp.com 