apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  # Staging environment specific settings
  interval: 15m  # Less frequent reconciliation for staging
  values:
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "200m"
    # Use two replicas for higher availability in staging
    replicas: 2
    # Enable metrics for monitoring
    metrics:
      serviceMonitor:
        enabled: true 