apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: sealed-secrets
spec:
  # Staging environment specific settings
  interval: 15m  # Less frequent reconciliation for staging
  chart:
    spec:
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: sealed-secrets
  values:
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        cpu: 200m
    # Use two replicas for higher availability in staging
    replicaCount: 2
    # Enable metrics for monitoring
    metrics:
      serviceMonitor:
        enabled: true 