---
# This is a HelmRelease Custom Resource for Flux v2 GitOps
# ENVIRONMENT-SPECIFIC: This may need adjustment based on your GitOps implementation
#
# Installation Options:
# 1. Flux v2: Use this HelmRelease as is (adjust sourceRef namespace if needed)
# 2. ArgoCD: Convert to Application CR or use helm chart directly
# 3. Manual: Use helm CLI with the values.yaml file
#    helm template gatekeeper/gatekeeper --values values.yaml | kubectl apply -f -
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
  annotations:
    # ENVIRONMENT-SPECIFIC: These annotations can be extended in environment overlays
    # Force reconciliation to pick up the new RBAC settings
    reconcile.fluxcd.io/requestedAt: "2025-03-04T10:45:00Z"
    environment.config/description: "OPA Gatekeeper for policy enforcement"
spec:
  # ENVIRONMENT-SPECIFIC: Adjust interval based on environment
  # - local/dev: shorter intervals (5m)
  # - staging/prod: longer intervals (15m+)
  interval: 5m
  chart:
    spec:
      chart: gatekeeper
      # ENVIRONMENT-SPECIFIC: Consider pinning to specific version in production
      version: 3.14.0
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        # ENVIRONMENT-SPECIFIC: Update namespace if needed for your GitOps setup
        namespace: flux-system
  # ENVIRONMENT-SPECIFIC: These values can be overridden in environment overlays
  values:
    # Values below can be customized per environment, these are just base settings
    replicas: 1
    auditInterval: 30
    logLevel: INFO
    
    # Explicitly enable RBAC to fix permission issues
    rbac:
      create: true
      
    # Configure service account
    serviceAccount:
      create: true
      name: "gatekeeper-admin"
      
    # Fix permissions for the default service account
    clusterRoles:
      - name: gatekeeper-manager-role
        rules:
          - apiGroups: ["*"]
            resources: ["*"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["admissionregistration.k8s.io"]
            resources: ["validatingwebhookconfigurations"]
            verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
          - apiGroups: [""]
            resources: ["secrets"]
            verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
            
    # ENVIRONMENT-SPECIFIC: Validation settings
    validatingWebhook:
      enabled: true
      
    # ENVIRONMENT-SPECIFIC: Security settings
    certRotation:
      enabled: true
      
    # ENVIRONMENT-SPECIFIC: Resource settings - adjust based on environment needs
    controllerManager:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    audit:
      resources:
        limits:
          cpu: 1000m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
    webhook:
      enabled: true

---
# ENVIRONMENT-SPECIFIC: This HelmRepository is for Flux v2
# In environments not using Flux or using a different namespace, this should be adjusted
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: gatekeeper
  namespace: flux-system
  annotations:
    # ENVIRONMENT-SPECIFIC: This may need to be adjusted for different environments
    environment.config/description: "Repository for OPA Gatekeeper Helm charts"
spec:
  interval: 1h
  url: https://open-policy-agent.github.io/gatekeeper/charts 