apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common labels for all test-app resources
commonLabels:
  app: test-app
  environment: staging

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml 