apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Core infrastructure components
  - cert-manager/
  - sealed-secrets/
  - vault/
  - ingress/
  - gatekeeper/
  - minio/
  - metallb/
  # Additional components
  - policy-engine/
  - security/ 