apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base vault configuration
resources:
- ../../../base/infrastructure/vault

# Apply local-specific patches
patchesStrategicMerge:
- patches/ingress-patch.yaml
- patches/vault-patch.yaml

# Import local-specific values
configMapGenerator:
- name: vault-values
  behavior: merge
  files:
  - values.yaml=helm/values.yaml 