apiVersion: v1
kind: Secret
metadata:
  name: tempo-aws-credentials
  namespace: observability
  # In a real environment, this would be managed by a secrets management solution
  # such as SealedSecrets, External Secrets, or HashiCorp Vault
type: Opaque
stringData:
  # These are placeholder values that should be replaced
  # IMPORTANT: Do not store real credentials in Git
  AWS_ACCESS_KEY_ID: "replace-with-real-access-key-id"
  AWS_SECRET_ACCESS_KEY: "replace-with-real-secret-access-key" 