apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tempo-pdb
  namespace: observability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/name: tempo 