apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 5m
  chart:
    spec:
      chart: ingress-nginx
      version: "4.4.x"
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
        namespace: flux-system
  install:
    crds: Skip
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controller:
      service:
        type: LoadBalancer
      metrics:
        enabled: false
        serviceMonitor:
          enabled: false
          additionalLabels: {}
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
    defaultBackend:
      enabled: false
    serviceMonitor:
      enabled: false
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: ServiceMonitor
              name: .*
            patch: |
              $patch: delete
              kind: ServiceMonitor
              metadata:
                name: placeholder 